jitsi/jicofo

resources/collect-dump-logs.sh
updated collect dump script to include heap dumps from OOM crashes if they are present in /tmp
This script now grabs any heap dumps from /tmp if the running process isn't found.  This is intended to cover the case in which the java process crashed due to an out of memory error and we wish to collect the resulting dump for analysis.
=> updated collect dump script with OOM heap dumps

resources/collect-dump-logs.sh
This is a safer version of the collect dumps scripts, which properly handles more than one memory dump, and correctly checks for a running java process before choosing whether to dump the live process or look for OOM dumps.
=> OOM fixes for collect dump scripts

resources/install/debian/init.d
Fixes stop of init script to work even if process is missing, otherwise it even fails to uninstall.
=> Fixes stop of init script to work even when process is missing.

src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/rest/Health.java
If you run Jicofo locally open http://localhost:8888/about/health?list_jvb=true to see Jitsi videobridges known to your Jicofo instance.
=> Optionally returns JVB list in REST health response.

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java, src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java, src/main/java/org/jitsi/jicofo/JitsiMeetServices.java, src/main/java/org/jitsi/jicofo/JvbDoctor.java, src/test/java/org/jitsi/jicofo/PubSubBridgeSelectorTest.java
This PR adds improvements to JVB health-check handling and also fixes an issue where JVB will not be rediscovered through PubSub even though it's sending correct stats. That's because bridge state was not cleared in https://github.com/jitsi/jicofo/commit/9cc8a6cb9678a8908e144e2152072ded2325781e#diff-80f25cc18c7310215af69b04ba73f331R556 when health-check has failed.
=> Pubsub rediscovery fix

src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java
bridges.remove() must be called before we propagate bridgeWentOffline, so that we clear internal state and won't handle the event second time.
=> Fixes ConcurrentModificationException on shutdown

pom.xml, src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JvbDoctor.java
Few improvements to health check handling:
a) allows to disable health-checks
b) gives a check another try on 1st request timeout
c) does not expire channels on faulty bridge, as the request will most likely fail anyway
d) sends health-check failed event asynchronously, so that the health check task does not cancel itself. When it does the Thread has "interrupted" flag set to true which will fail next event handlers who try to send any XMPP packet with Smack(EventAdmin.sendEvent executes on caller's thread).
=> Healthcheck improvements

pom.xml, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java
instead of copying the url provided in the user request.
=> Sets only the name of the conference room in Jibri START IQ

src/main/java/org/jitsi/jicofo/VersionBroadcaster.java
This PR should fix a deadlock described by the thread dump at the bottom.
In order to fix that I removed the synchronised from start/stop/handleEvent. The reason for that is that it's not a problem when two events will execute at the same time and originally these synchronised statements were protecting against simultaneous execution of start()/stop() and handleEvent(), but probably that does not make sense since OSGi executes BundleActivator.start/stop synchronously. Also if OSGi is being stopped then EventAdmin will also be stopped,so handleEvent will not be invoked.
Java stack information for the threads listed above:
===================================================
"qtp1020005132-349":
at org.jitsi.jicofo.FocusManager.getConference(FocusManager.java:419)
- waiting to lock …
=> Removes synchronized statements from VersionBroadcaster

pom.xml
Quickly run tested with Firefox Nightly 46 and Chrome 47
Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>
=> Update bcprov-jdk15on to 1.54

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java
- update jitsi-protocol-jabber to fix RTP description updates(Firefox support was broken because of that)
- log in debug mode Colibri "channel allocate request"
=> Fix broken FF support

pom.xml, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/discovery/DiscoveryUtil.java, src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java
Cleans up JingleOfferFactory. Removes RED, ULPFEC and some unused audio formats from the offer, and adds RTX. RTX is optionally disabled on a per-conference basis by setting disableRtx=true in the conference creation request (or adding #config.disableRtx=true to the URL in Jitsi-Meet).
Note: this needs jitsi-videobridge#209 (not directly, but stuff will be broken without it).
=> Adds RTX by default to offers

src/main/java/org/jitsi/impl/protocol/xmpp/DefaultJingleRequestHandler.java, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/ConferenceUtility.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/JingleRequestHandler.java, src/main/java/org/jitsi/protocol/xmpp/OperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java
This PR makes Jicofo move the conference to another bridge when the current one dies. This is done by sending 'transport-replace' message to the client which contains transport info for the new bridge.
=> Restart the conference without reloading the page

src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCSignaling.java
SSRC parameters are no longer included in removed SSRC's
description as we don't want the clients to care about them.
=> Simplify 'source-remove' notification

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/JvbDoctor.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/discovery/DiscoveryUtil.java, src/main/java/org/jitsi/jicofo/recording/JireconRecorder.java, src/main/java/org/jitsi/jicofo/recording/JvbRecorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java
This PR uses IQUtils to print response XML to handle "null" response case. It also bumps Jicoco version which will result in having some other changes merged like InfluxDb version upgrade.
=> Avoid NPE when XMPP response is null

pom.xml, src/main/java/org/jitsi/jicofo/JitsiMeetGlobalConfig.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriDetector.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/test/java/org/jitsi/jicofo/FocusTestSuite.java, src/test/java/org/jitsi/jicofo/xmpp/JibriIqProviderTest.java
Implements new Jibri states:
- "failed": when Jibri recorder fail with an erron it will send it to Jicofo which will then forward it to the client in the "failed" state
- "busy": when there are Jibris connected to the system, but all are currently in "busy" state then Jicofo will broadcast "busy" state instead of "undefined"
=> Jibri busy and error

src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java
Avoids throwing NPE in ColibriConferenceImpl when there is no 'jitsiVideobridge' set, but logs an error instead.
=> Avoid throwing NPE in ColibriConferenceImpl

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolActivator.java
Seems like the default one equal to 5 seconds will often timeout slower clients on session-invite.
=> Increase default packet timeout to 15 seconds

src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java, src/main/java/org/jitsi/jicofo/JvbDoctor.java
Handles PubSub notification containing <service-unavailable/> element inserted by the Prosody plugin when it detects that the component has been disconnected to react to bridge shutdown/restart faster.
=> Component disconnected

src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java
Still having a bit of trouble testing this because of a problem with Jibri (if I kill the XMPP process, ffmpeg doesn't get cleaned up and continues recording, so any New Jibris that are selected can't send to YouTube because it's already in use), but I think it's working now. It's definitely retrying with a different Jibri anyways.
=> HQL-1502: Retry recording with new Jibri on fail

src/main/java/org/jitsi/jicofo/LipSyncHack.java
A complementary hack has been implemented in the JVB which allows to merge the streams, even if the video is muted.
UPDATE: The complementary hack is here https://github.com/jitsi/jitsi-videobridge/pull/277. Please do not merge this until the JVB hack has been merged.
=> Enable the LS hack when video muted.

src/main/java/org/jitsi/jicofo/rest/Health.java
We need to log the exact reason for the health check failure, as there aren't any details included in the response.
=> Log health check exceptions

src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java
When two threads remove Jingle sessions at the same that strange things may happen. Trying to fix:
Jicofo 2016-08-30 07:05:25.911 WARNING: [13] org.jitsi.jicofo.FocusManager.expireLoop().661 Error while checking for timeouted conference
java.lang.NegativeArraySizeException
at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
at java.util.ArrayList.<init>(ArrayList.java:177)
at org.jitsi.protocol.xmpp.AbstractOperationSetJingle.terminateHandlersSessions(AbstractOperationSetJingle.java:540)
at org.jitsi.jicofo.JitsiMeetConference.stop(JitsiMeetConference.java:350)
at org.jitsi.jicofo.FocusManager$FocusExpireThread.expireLoop(FocusManager.java:655)
at org.jitsi.jicofo.FocusManager$FocusExpireThread.access$000(FocusManager.java:543)
at …
=> fix(AbstractOperationSetJingle): NegativeArraySizeException

src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java
The conference might have stopped, before PacketListener is executed
and user's MUC role is no longer available. It's fine to just abort the
operation.
Trying to fix:
Jicofo 2016-08-29 20:10:43.041 SEVERE: [36] org.jivesoftware.smack.Connection.notifyListener() null
java.lang.NullPointerException
at org.jitsi.jicofo.JitsiMeetConference.getRoleForMucJid(JitsiMeetConference.java:849)
at org.jitsi.jicofo.MeetExtensionsHandler.handlePresence(MeetExtensionsHandler.java:469)
at org.jitsi.jicofo.MeetExtensionsHandler.processPacket(MeetExtensionsHandler.java:154)
at org.jivesoftware.smack.Connection$ListenerWrapper.notifyListener(Connection.java:867)
at org.jivesoftware.smack.PacketReader$ListenerNotification.run(PacketReader.java:457)
at …
=> fix(MeetExtensionsHandler): fix NPE on get user role

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/protocol/xmpp/ChatRoom2.java, src/test/java/mock/muc/MockMultiUserChat.java
A continuation of https://github.com/jitsi/jicofo/pull/116
It turns out that the warning added in the previous PR is now logged too often, because it also includes the presence packets of Jicofo itself. This PR will ignore these packets as we're not interested in processing them in the MeetExtensionsHandler.
=> Less verbose log

src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetGlobalConfig.java, src/main/java/org/jitsi/jicofo/LipSyncHack.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/OperationSetJingle.java
After the call ends the person who remains alone in the room will have it's media session expired after 20 seconds to prevent from wasting the bandwidth/resources.
=> Timeout lonely participant's media session who remain in the MUC

pom.xml
EntityCapsManager class was ignoring Presence packets without the 'c'
extension and not cleaning up map entries. The issue occurs when used
with Prosody nightly 683 and later. We don't know the exact version when
the problem started, but 652 was fine.
=> Update protocol-jabber to fix capabilities related memory leak

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/extensions/AbstractIQ.java
This PR fixes Jicofo breaking it's own XMPP connection when includes unescaped text in XML attributes of some IQs.
=> Fix not-well-formed error

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/ChatRoomRoleAndPresence.java, src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetRecording.java, src/main/java/org/jitsi/jicofo/LipSyncHack.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/ProtocolProviderHandler.java, src/main/java/org/jitsi/jicofo/recording/JireconRecorder.java, src/main/java/org/jitsi/jicofo/recording/JvbRecorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/jicofo/rest/Health.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCSignaling.java
This PR silences out the logs produced during Jicofo health checks. Also gets rid of some not very useful logs left for debugging purpose of the issues which are no longer present.
=> No healthcheck logs

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/ChatRoomRoleAndPresence.java, src/main/java/org/jitsi/jicofo/JvbDoctor.java, src/main/java/org/jitsi/jicofo/LipSyncHack.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/discovery/DiscoveryUtil.java, src/main/java/org/jitsi/jicofo/recording/JireconRecorder.java, src/main/java/org/jitsi/jicofo/recording/JvbRecorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriDetector.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/OperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/XmppConnection.java, src/test/java/mock/xmpp/colibri/AllocThreadingTestColibriConference.java
1. fixes some threads dying while trying to send packets on broken XMPP connection(may lead to weird state left)
2. fixes invalid Jibri addresses kept in the memory after XMPP reconnection
=> Fix problems in JibriDetector on XMPP reconnect

pom.xml, src/main/java/org/jitsi/jicofo/xmpp/FocusComponent.java, src/test/java/org/jitsi/jicofo/ShutdownTest.java, src/test/java/org/jitsi/jicofo/XmppTest.java
Updates Jicoco in order to measure packet processing time in the XMPP component.
=> Measure XMPP packet processing time

src/main/java/org/jitsi/impl/protocol/xmpp/OpSetSubscriptionImpl.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/ChatRoomRoleAndPresence.java, src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java, src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetRecording.java, src/main/java/org/jitsi/jicofo/JitsiMeetServices.java, src/main/java/org/jitsi/jicofo/JvbDoctor.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/VersionBroadcaster.java, src/main/java/org/jitsi/jicofo/auth/AuthenticationSession.java, src/main/java/org/jitsi/jicofo/recording/JireconRecorder.java, src/main/java/org/jitsi/jicofo/recording/Recorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/jicofo/rest/Health.java, src/main/java/org/jitsi/protocol/xmpp/JingleSession.java, src/main/java/org/jitsi/protocol/xmpp/util/MediaSSRCMap.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCGroup.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCSignaling.java, src/test/java/org/jitsi/jicofo/MockJitsiMeetConference.java, src/test/java/org/jitsi/jicofo/ParticipantTest.java
Prevents from allowing to inject multiple SSRCs for the same media stream id. Logs an error when such case is detected.
=> Stream duplicates

src/main/java/org/jitsi/jicofo/Participant.java, src/test/java/org/jitsi/jicofo/ParticipantTest.java
SSRC groups used  in simulcast have to be taken into account in the SSRC duplicates detection.
=> Temporarily disable SSRC duplicates detection

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java
Fixes:
Jicofo 2016-11-17 20:39:04.842 SEVERE: [15] org.jitsi.jicofo.ProtocolProviderHandler.registrationStateChanged().142 null
java.lang.NullPointerException
at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.discoverItems(XmppProtocolProvider.java:488)
at org.jitsi.impl.protocol.xmpp.OpSetSimpleCapsImpl.getItems(OpSetSimpleCapsImpl.java:53)
at org.jitsi.jicofo.ComponentsDiscovery.discoverServices(ComponentsDiscovery.java:236)
at org.jitsi.jicofo.ComponentsDiscovery.firstTimeDiscovery(ComponentsDiscovery.java:306)
at org.jitsi.jicofo.ComponentsDiscovery.registrationStateChanged(ComponentsDiscovery.java:341)
at org.jitsi.jicofo.ProtocolProviderHandler.registrationStateChanged(ProtocolProviderHandler.java:138)
at net.java.sip.communicator.service.protocol.AbstractProtocolProviderService.f …
=> Fix NPE in XmppProtocolProvider when fails to login

pom.xml
With a "test" scope the ice4j jar is not included in the package,
resulting in (probably harmless) class not found errors:
java.lang.NoClassDefFoundError: org/ice4j/stack/PacketLogger
at
net.java.sip.communicator.impl.netaddr.NetaddrActivator.start(NetaddrActivator.java:85)
at
org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:293)
at
org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:460)
at
org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:126)
at
org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:111)
at
org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:17)
at
org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:220)
=> mvn: Changes the scope of the ice4j dependency.

src/main/java/org/jitsi/impl/reservation/rest/RESTReservations.java
I am using Jicofo's reservation system to generate a PIN to each conference to integrate with Jigasi.
However, I get a NPE in [this line](https://github.com/jitsi/jicofo/blob/8f165d52b2cf4d34925de09e120fb13632ebcd18/src/main/java/org/jitsi/impl/reservation/rest/RESTReservations.java#L201) for every new conference. 
Looking at the code, I found out that the reason for getting a NPE is that identity/creator variable is set to null by default in [this line](https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/xmpp/FocusComponent.java#L361) and it does not change its value if there is no authentication system, which is my case.  
This PR allows the conference to be created when there isn't an authentication system. 
Tell me if this is not a desirable behavior, so I can …
=> Fix NPE in reservation system when there's no authAuthority

src/main/java/org/jitsi/impl/protocol/xmpp/DefaultJingleRequestHandler.java, src/main/java/org/jitsi/jicofo/InvalidSSRCsException.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/SSRCValidator.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/JingleRequestHandler.java, src/main/java/org/jitsi/protocol/xmpp/util/MediaSSRCGroupMap.java, src/main/java/org/jitsi/protocol/xmpp/util/MediaSSRCMap.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCGroup.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCSignaling.java, src/test/java/org/jitsi/jicofo/ParticipantTest.java
Checks the following, before accepting SSRCs to the conference description:
1. Allow SSRC value between 1 and 0xFFFFFFFF
2. Do not allow the same SSRC to appear more than once per media type
3. Skip SSRCs if the SSRC count limit is exceeded
4. Filter out SSRC parameters other than 'cname' and 'msid'
5. Drop empty SSRC groups
6. Skip duplicated groups (the same semantics and SSRCs)
7. Look for MSID conflicts between SSRCs which do not belong to the same
group
8. Make sure that SSRCs described by groups exist in media description
Some of the above were checked even before the PR changes.
=> Verify SSRCs and groups

src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java
ScheduledExecutorService has the functionality to catch any Error coming out of the Runnable run method and swallow it without printing anything.
=> Catches all errors in Runnables passed to ScheduledExecutorService.

src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java
The feature has been replaced so the option no longer applies.
=> cleanup: remove adaptive last N config option

src/main/java/org/jitsi/jicofo/SSRCValidator.java, src/test/java/org/jitsi/jicofo/ParticipantTest.java
SSRCValidator will make sure that any grouped SSRC has an MSID and that it's the same across the group.
=> SSRCValidator will require one MSID across the SSRC group

src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java
Chrome is rejecting the abs-send-time for audio (not sure when that
started, but it's expected since they're moving away from receiver side
bandwidth estimations), but since it's singnaled through COLIBRI to the
bridge, the bridge adds it to outgoing RTP audio packets, which causing
the client to flood the verbose console logs with:
[32136:46627:0314/121945.923995:WARNING:rtp_utility.cc(342)] Failed to
find extension id: 3
=> fix: Remove abs-send-time from audio.

src/main/java/org/jitsi/jicofo/BridgeSelector.java
This PR fixes an issue where during conference burst many "video stream count added/removed" events would be queued onto the single threaded queue and then those are processed, after let's say 0 is received through PubSub. So even though those events were generated before the PubSub they will be effective, but they should not. This change will make the incoming PubSub stats overwrite outdated values (before the change they would overwrite it only if the stream count has changed).
=> Quick fix for conference burst

src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/FocusBundleActivator.java, src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java, src/test/java/org/jitsi/jicofo/ColibriTest.java, src/test/java/org/jitsi/jicofo/ColibriThreadingTest.java, src/test/java/org/jitsi/jicofo/ParticipantTest.java
Video content creation is parametrizable via some configuration
options, so these methods need access to the ConfigurationService
that is discovered and initialized in the FocusBundleActivator start.
After the ConfigurationService is initialized, we initialize the
JingleOfferFactory and we also make it a static member of the
FocusBundleActivator, just like the ConfigurationService.
=> ref: Makes some of the JingleOfferFactory methods non-static.

src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/recording/Recorder.java, src/main/java/org/jitsi/jicofo/util/QueuePacketProcessor.java
Moves incoming xmpp packet processing in new thread to avoid blocking packet reader thread. This causes problems with certain features like jigasi. Sending a message to jigasi and witing for response, while in the meantime jigasi is sending packets can lead for waiting for a timeout till we process other incoming packets.
=> Moves processing incoming xmpp packets in new thread.

src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java
to offers (if the org.jitsi.jicofo.ENABLE_FRAMEMARKING property is set
to true).
=> feat: Adds the framemarking header extension

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetRecording.java, src/main/java/org/jitsi/jicofo/recording/Recorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java
JibriRecorder will no longer extend deprecated Recorder. Also JibriRecorder instance lifetime will no longer be tied to the lifetime of a Colibri conference on the JVB. That's because it needs
to report Jibri availability even if the conference has expired. For example when there's just one participant left and the JVB conference is being expired.
=> Deprecate Recorder

src/main/java/org/jitsi/impl/protocol/xmpp/ChatMemberImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolActivator.java, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java, src/main/java/org/jitsi/impl/protocol/xmpp/extensions/RegionPacketExtension.java, src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/BridgeState.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/ConferenceUtility.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java, src/main/java/org/jitsi/jicofo/JitsiMeetRecording.java, src/main/java/org/jitsi/jicofo/JvbDoctor.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/VersionBroadcaster.java, src/main/java/org/jitsi/jicofo/recording/JireconRecorder.java, src/main/java/org/jitsi/protocol/xmpp/OperationSetSubscription.java, src/main/java/org/jitsi/protocol/xmpp/XmppChatMember.java, src/test/java/mock/muc/MockRoomMember.java, src/test/java/mock/util/TestConference.java, src/test/java/org/jitsi/jicofo/BridgeSelectorTest.java, src/test/java/org/jitsi/jicofo/JvbDoctorTest.java, src/test/java/org/jitsi/jicofo/MockJitsiMeetConference.java
Uses a list of bridges and refactors the invitations process to take
this into account.
This is in preparation for support for multi-bridge support (currently
the bridge selection algorithm is unmodified).
=> Refactors JitsiMeetConferenceImpl

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/protocol/xmpp/ChatRoom2.java, src/test/java/mock/muc/MockMultiUserChat.java
Fixes problem with infinite loop when bridge is in the graceful shutdown mode.
=> fix(ChannelAllocator): break the loop if the jvb has failed

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolActivator.java
This commit prevents the default SOCKS5 proxy (from Smack) from being started.
=> Don't start an unused SOCKS5 proxy.

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/ChatMemberImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolActivator.java, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/protocol/xmpp/XmppChatMember.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java, src/test/java/mock/muc/MockRoomMember.java, src/test/java/org/jitsi/jicofo/ColibriTest.java, src/test/java/org/jitsi/jicofo/ColibriThreadingTest.java
Changes colibri to use <endpoint and stops using <channel-bundle. Uses statsId if available.
=> Introduces StatsId and colibri changes around it

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolActivator.java, src/main/java/org/jitsi/impl/protocol/xmpp/extensions/ConferenceIqProvider.java
Fixes a problem where if there is a parse error the connection to the xmpp server is dropped and no more conferences are possible.
=> Connection closed error

src/main/java/org/jitsi/jicofo/xmpp/FocusComponent.java
Smack currently do not support errors without text and NPE is thrown
when operating over these stanzas. There is a PR to fix that https://github.com/igniterealtime/Smack/pull/178
=> Uses an error message to prevent NPE in smack.

resources/install/debian/postinst
java.nio.file.FileSystemException: /etc/jitsi/jicofo: Operation not permitted
=> Fixes 'Operation not permitted' on startup.

src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java
Fixes a sync issue where when we decide to give up waiting for jibri and
mark it as stopped, jibri enters the room. We make sure we send stop to
it if we stop waiting.
=> Simplifies stop logic.

src/main/java/org/jitsi/impl/protocol/xmpp/extensions/LogoutIq.java
Fixes error when authentication is enabled and you try to logout:
Jicofo 2017-12-13 10:57:25.604 SEVERE: [80] org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl().325 org.dom4j.DocumentException: Error on line 1 of document  : Element type "logout" must be followed by either attribute specifications, ">" or "/>". Nested exception: Element type "logout" must be followed by either attribute specifications, ">" or "/>".
org.dom4j.DocumentException: Error on line 1 of document  : Element type "logout" must be followed by either attribute specifications, ">" or "/>". Nested exception: Element type "logout" must be followed by either attribute specifications, ">" or "/>".
at org.dom4j.io.SAXReader.read(SAXReader.java:482)
at org.dom4j.io.SAXReader.read(SAXReader.java:365)
at …
=> Fixes logoutIQ to xml/string.

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/SSRCValidator.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCSignaling.java, src/test/java/org/jitsi/jicofo/SSRCValidatorTest.java
SSRCValidator used to check SSRC correctness only on per each participant basis, but it will not catch all of the problems. All sources have to be checked as a whole, from all participants, as this gets merged into one remote SDP on the client.
=> Fix SSRC validation

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java, src/main/java/org/jitsi/jicofo/FocusManager.java
When jicofo connects to the XMPP domain, it uses a default, Smack-provided
implementation that controls verification and validation of the server-provided
TLS certificate. In certain setups, it is desirable to override this behavior,
and allow any certificate that's provided.
This commit adds an option that, once enabled, causes Jicofo to trust any and
all certificate that is provided by the XMPP server that it conntects to.
=> Add option to always trust XMPP domain certificate.

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java
Focus fails to connect when other SASLMechs are offered by Openfire. This should address #203
=> Fix #203 - Disables GSSAPI

src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java
later on down this chain we need to send a stop messages and, if the jid
is already null we exit early.  there was one path that could exit
return before we reached that point, so it needs its own null
assignment.
=> don't reset currentJibriJid to null too soon

pom.xml
Using https://github.com/jitsi/Smack/tree/4.2.2-jitsi. 
Fixes a memory leak in muc manager.
=> Updates smack to 4.2.2-jitsi.

src/main/java/org/jitsi/jicofo/recording/jibri/JibriDetector.java
We're seeing Jicofo randomly report Jibris as going offline.  Jicofo will think a Jibri went offline if it gets an 'undefined' status extension from Jibri, so adding a log here to see if that's what may be going on.
=> add a log when we receive a jibri status

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
When starting/joining a MUC fails, 'leave' is called as part of the
exception handling. In case 'leave' throws an exception, this exception
should not be thrown instead of the original exception that was thrown
when start failed.
=> fix: prevent hiding original exception when MUC start fails.

.gitignore
This is in line with what the videobridge project has.
=> fix: add IntelliJ's metadata to .gitignore

src/main/java/org/jitsi/impl/protocol/xmpp/extensions/ConferenceProperties.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
This commit adds a generic PresenceElement Packet Extension in the
http://jitsi.org/protocol/focus namespace for simple name/value fields that
can be added in Presence. The name of the field is the name of the
element and the value of the field is set in the element text.
=> feat: Adds a presence element that can hold simple name/value fields.

src/main/java/org/jitsi/jicofo/auth/AbstractAuthAuthority.java
It is fine for the read-only methods to not lock the syncRoot. This
tries to fix the following deadlock:
Found one Java-level deadlock:
=============================
"pool-7-thread-17":
waiting to lock monitor 0x00007f1c780375a8 (object 0x000000070048bdf0, a java.lang.Object),
which is held by "pool-7-thread-10"
"pool-7-thread-10":
waiting to lock monitor 0x00007f1c78035ef8 (object 0x0000000782512f08, a java.util.HashMap),
which is held by "Smack-Single Threaded Executor 0 (0)"
"Smack-Single Threaded Executor 0 (0)":
waiting to lock monitor 0x00007f1c780375a8 (object 0x000000070048bdf0, a java.lang.Object),
which is held by "pool-7-thread-10"
Java stack information for the threads listed above:
===================================================
"pool-7-thread-17":
at …
=> ref(AbstractAuthAuthority): relax sync on read methods

README.md
This patch saves users the trouble of having to find the Jitsi-Meet `config.js` file after installation from the Debian packages (same as is done for the Prosody config files in step #1 of the Secure Domain instructions).
=> Provide default location of Jitsi-Meet config.js

src/test/java/mock/jvb/MockVideobridge.java
the tests do things like create conferences/channels and then verify how
many were created, but the mock bridge runs health checks which creates
conferences and channels on its own.  this adds a helper to get only the
conferences manually created (not the health-check-created ones)
=> add a helper to get non-health check conferences

src/main/java/org/jitsi/jicofo/recording/jibri/JibriDetector.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java
If a jibri session encounters an error, we'll try and find another
available jibri to continue the current service.
=> Try to fallback to another Jibri in case of an error

src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/jigasi/JigasiDetector.java
Retries sending rayo iq two times. Hitting timeout waiting for response
returns null reply, then we retry till we exhaust the attempts, receive
a reply, there is an exception or there are no more instances to try. We
filter the instances we already tried when selecting new one.
=> Retries sending rayo iq.

src/main/java/org/jitsi/jicofo/AbstractChannelAllocator.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/Participant.java
First commit adds a method which does the cleanup when Participant is removed from BridgeSession.
The second one removes unnecessary code which was duplicating the failure handling from the channel allocator. When Jicofo fails to allocate channels it always calls onBridgeDown which effectively does what's been done in the methods removed.
=> Optimizations around participant re-invite and failure handling

src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java
=> try to fallback to another jibri when the current one's pending timeout

src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java
the previous code was causing an issue where we'd compare the same JID
content (but different references) and Jicofo thought they weren't the
same.
=> use compareTo when comparing Jids

pom.xml, src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java
Relands https://github.com/jitsi/jicofo/pull/335 with the correct LJ version.
=> Relands support for the video content type header extension.

src/main/java/org/jitsi/jicofo/auth/AuthBundleActivator.java
When we enable the shibboleth authentication the health check REST API stop to work.
All HTTP requests are first processed by the Shibboleth Jetty Handler and this handler rejects the /about/health request du to missing auth mandatory parameter. 
The solution to enable health REST API and shibboleth is to switch jetty handlers order so HTTP request are firstly computed with the health-check handler and if the request is not an health-check it is then computed by the shibboleth part.
=> Fix : use of health-checks REST API with Shibboleth authentication

pom.xml
for some reason, having it in the test scope caused conflicts in
sub-libraries and led to  issues with jetty starting  up,  but  having
it outside that scope  seems  to fix it.
=> change the ice4j dependency to not be in only  test scope

src/test/java/mock/jvb/MockVideobridge.java
This PR is an code adaption to changes proposed in https://github.com/jitsi/jitsi-videobridge/pull/927, where `getOrCreateLocalEndpoint` has been removed and replaced with two dedicated methods `getLocalEndpoint` and `createLocalEndpoint`.
This changes are backward compatible, so it is not necessary to wait until https://github.com/jitsi/jitsi-videobridge/pull/927 is merged to merge this PR.
=> Avoid usage of Videobridge.getOrCreateLocalEndpoint method

pom.xml, src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/auth/AuthBundleActivator.java, src/main/java/org/jitsi/jicofo/rest/Application.java, src/main/java/org/jitsi/jicofo/rest/Statistics.java, src/main/java/org/jitsi/jicofo/util/FocusManagerProvider.java, src/main/java/org/jitsi/jicofo/util/OsgiServiceBinder.java, src/main/java/org/jitsi/jicofo/util/OsgiServiceProvider.java
This PR adds a `/stats` REST endpoint in Jicofo to expose conference count, largest conference size, and a conference sizes histogram.  Previously, this data was being retrieved from the bridge, but due to Octo the bridge is unable to give reliable information, as it doesn't have the complete picture.
I added Jersey here to handle this; I've already updated all the REST code in the bridge to use it and I think it'd make sense to port over the other Jicofo endpoints, but I refrained from doing that as part of this work--though I can take a look at doing that in an immediate follow-up PR for consistency.
=> Add a /stats REST endpoint to Jicofo, expose some data

src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/rest/Statistics.java, src/main/java/org/jitsi/jicofo/stats/JicofoStatisticsSnapshot.java, src/main/java/org/jitsi/jicofo/stats/Statistics.java
(This is built on top of the code in https://github.com/jitsi/jicofo/pull/401, so the first 3 commits here will go away once that is merged and I rebase).
This adds tracking for the current number of participants and the total number of participants since start.  I don't know if `FocusManager` is the best place to be the central location for stats, but it seemed reasonable so let me know if somewhere else would be appropriate.
=> Track num participants/total num participants

pom.xml
jitsi-utils was split into 2 repos (`jitsi-utils` and `jitsi-utils-kotlin`).  We need to update to a version which includes that change in order for the tests which depend on jvb to work.
=> Update jitsi-utils to work with new format

src/main/java/org/jitsi/jicofo/auth/AuthBundleActivator.java, src/main/java/org/jitsi/jicofo/auth/ShibbolethHandler.java
since the servlet has a path spec of '/*', it matches all urls and, if
it doesn't end up handling a request, that request is still marked as
'handled' so it doesn't fall through to the next handler.
now, we'll move the shibboleth handler first but make sure it handles
only the shibboleth urls: all others will not be marked as handled and
will fall through to the next handler.
addresses https://github.com/jitsi/jicofo/issues/404
=> fix the shibboleth web handler

src/main/java/org/jitsi/jicofo/auth/AuthBundleActivator.java, src/main/java/org/jitsi/jicofo/rest/Application.java, src/main/java/org/jitsi/jicofo/rest/Health.java, src/main/java/org/jitsi/jicofo/rest/Statistics.java, src/test/java/org/jitsi/jicofo/rest/HealthTest.java
Before the change health check that returns jvb list (curl -v http://localhost:8888/about/health?list_jvb=true), in case of components returns:
`The JID 'jitsi-videobridge.jitsi.example.com' has no resourcepart (through reference chain: org.json.simple.JSONObject["jvbs"]->java.util.ArrayList[0]->org.jxmpp.jid.impl.DomainpartJid["resourceOrThrow"])`.
And in case of mucs returns:
`{"jvbs":[{"resourceOrNull":"damencho","localpartOrNull":"jvbbrewery","resourcepart":"damencho","localpart":"jvbbrewery","domain":"internal.auth.jitsi.example.com","domainBareJid":false,"entityBareJid":false,"entityJid":true,"domainFullJid":false,"entityFullJid":true,"resourceOrEmpty":"damencho","resourceOrThrow":"damencho","localpartOrThrow":"jvbbrewery"}]}`
After the change will return: …
=> Fix health returned jvb list

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/SSRCValidator.java, src/test/java/org/jitsi/jicofo/SSRCValidatorTest.java
When processing client's source remove notification, first tries to remove on conference state copy and prevents the modification if it results in a broken state.
=> fix: validate conference state on source removal

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/jicofo/recording/jibri/OperationSetJibri.java
In ChatRoomImpl and OperationSetJibri.
Should fix a deadlock.
(Note this changes some indentation; you may wish to review hiding whitespace changes.)
=> Move operations on items found in maps outside synchronized blocks.

src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetServices.java, src/main/java/org/jitsi/jicofo/ProtocolProviderHandler.java, src/main/java/org/jitsi/jicofo/bridge/BridgeMucDetector.java, src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java, src/main/java/org/jitsi/jicofo/util/FocusAccountFactory.java
The following properties can be used to add separate XMPP connection for
JVB communication:
org.jitsi.jicofo.BRIDGE_MUC=JvbBrewery@muc.jvb.server.com
org.jitsi.jicofo.BRIDGE_MUC_XMPP_HOST=jvb.server.com
org.jitsi.jicofo.BRIDGE_MUC_XMPP_USER_DOMAIN=auth.jvb.server.com
org.jitsi.jicofo.BRIDGE_MUC_XMPP_PORT=6222
org.jitsi.jicofo.BRIDGE_MUC_XMPP_USER=focus
org.jitsi.jicofo.BRIDGE_MUC_XMPP_USER_PASS=topsecret
=> feat: add dedicated XMPP connection for JVB communication

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
Note: it's possible more places need to use the new `operationalBridges()` method rather than use `bridges` directly, but this should be a start?
=> Don't consider failed and non-operational bridges for Octo.

src/main/java/org/jitsi/jicofo/auth/ShibbolethHandler.java
Replacing equals with startsWith should fix #446 for Shibboleth.
=> Shibboleth Authentification Fix

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java
This is to fix behaviour described at: https://community.jitsi.org/t/room-not-being-destroyed-after-duration-exceeded/29768
When reservation API sets duration for conference, this is not respected and room is not destroyed upon duration's expiry,
with error like that:
java.lang.RuntimeException: org.jxmpp.stringprep.XmppStringprepException: XmppStringprepException caused by 'null': org.jxmpp.stringprep.XmppStringprepException: Input 'domain' must not be null
=> Fixes room destruction after duration expires.

src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/recording/jibri/CommonJibriStuff.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSessionStats.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSipGateway.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriStats.java, src/test/java/org/jitsi/jicofo/MockJitsiMeetConference.java
Adds the following to the JSON stats:
"live_streaming_active" - active Jibri live streaming sessions
"recording_active" - active Jibri recording sessions
"sip_call_active" - active Jibri SIP calls
"live_streaming_pending" - pending live streaming Jibri sessions
"recording_pending" - pending recording Jibri sessions
"sip_call_pending" - pending SIP call Jibri sessions
=> feat(stats): add info about Jibri sessions

src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java
verifyHealthCheckSupport() calls to DiscoveryUtil.checkFeatureSupport
which is a blocking operation while waiting for disco info response.
=> fix(JvbDoctor): release the lock for feature discovery

src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java, src/main/java/org/jitsi/jicofo/FocusBundleActivator.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/util/DaemonThreadFactory.java
The scheduled ExecutorService pool shared by all Jicofo
components had a silly size of 20, so bump it to 200. Any timing out
requests can easily block the pipeline. This pool is used
by components that run things at fixed rate or schedule tasks
with delays.
Adds a cached ExecutorService and make channel allocator threads
use it instead of the scheduled executor pool which has limited size.
=> fix: re-arrange shared thread pools

src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java
There should be no need for that as now the bridges and other components use MUC.
=> ref: disable service rediscovery by default

src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/health/Health.java
Adds 'slow_health_check' key which will count how many health checks took more than 3 seconds to complete.
=> feat(stats): add 'slow_health_check'

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/JingleSession.java, src/main/java/org/jitsi/protocol/xmpp/OperationSetJingle.java
@JonathanLennox discovered an issue with Octo that could lead to broken rendering of Octo participants because we're not propagating the sources/source groups of a re-invited participants. That's fixed in the first commit.
In the second commit I remove sources/groups from octo, when a participant is terminated. I can't think of any side-effects if we don't do that, but it seems like a good idea to maintain a clean Octo state.
=> Propagate sources upon ice restart + some.

src/main/java/org/jitsi/jicofo/AbstractChannelAllocator.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
Cancels any pending octo allocations when the a bridge session is
terminated. This is fixes the following race as reported by @bgrozev:
1. A participant joins
2. We start an OctoChannelAllocator for a new bridge
3. We start a ParticipantChannelAllocator
4. The participant leaves (~150 ms after joining)
5. We cancel the ParticipantChannelAllocator
=> fix(octo): Prevents leaking of OctoEndpoint.

README.md
Since I enabled LDAP auth, the TURN/TURNS did not work. I came across this post: https://community.jitsi.org/t/cant-get-jitsi-meet-to-work-with-turn-solved/32300/14?u=webcf and this did the trick.
This PR adds this information.
=> Secure domain + Coturn - Need adapted instructions

src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java
Doing synchronous expire blocks Smack's Single Threaded
executor and builds up a delay on the processing queue.
It also may time out other jobs that are waiting for
a packet to arrive if the expire will block and timeout.
It's recommended to run the JVB2 with the IQ_HANDLER_MODE
set to 'sync' in the MUC configuration to have ICE restarts
working.
=> ref: remove sync channel expire

src/main/java/org/jitsi/impl/protocol/xmpp/PacketDebugger.java
Fixes total XMPP packets received counter
by enabling AbstractDebugger.printInterpreted.
Smack's TCP connection sends packets one by one,
but reads the text in batches without splitting
into packets. The option enables logging at
the later phase after the raw text was parsed to XML.
That's where the packets will be counted now.
=> fix(PacketDebugger): total totalPacketsRecv

src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/util/JicofoJingleUtils.java, src/test/java/org/jitsi/jicofo/BundleTest.java
removes the legacy
http://estos.de/ns/bundle
version of signaling bundle. This has been superseeded by
https://xmpp.org/extensions/xep-0338.html
=> remove pre-spec bundle signaling

src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/AbstractChannelAllocator.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/OctoChannelAllocator.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/ParticipantChannelAllocator.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java, src/test/java/mock/MockParticipant.java, src/test/java/mock/muc/MockRoomMember.java, src/test/java/org/jitsi/jicofo/BundleTest.java, src/test/java/org/jitsi/jicofo/ColibriTest.java, src/test/java/org/jitsi/jicofo/ColibriThreadingTest.java
Non-bundle support was deprecated in JVB 2, so we no longer support clients doing anything short of max-bundle.  These changes throw an exception if a participant does not list bundle among its advertised features, and assumes all clients are using bundle everywhere else (which meant removing many flags/conditionals to distinguish between bundle and non-bundle cases).
=> Require bundle

pom.xml
So jitsi-utils's versions of maven dependencies wins.
=> List jitsi-utils before jitsi-desktop dependencies.

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
The idleTimestamp must be set before the call to 'joinTheRoom', because it triggers participants joined events and the timestamp is not set to -1.
=> fix: idle timeout if participants in the room

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/rest/Statistics.java
We want to track how long it takes for the allocate request to complete, as we're looking at a new transport for this path and want to have some data to compare.
@bgrozev I know we talked about doing this for health checks as well, but we have some logic there that [retries](https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java#L453-L483) and I wasn't sure what we want to do there, so thought I'd at least start with this bit.
=> track how long it takes to allocate channels on the jvb

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
We noticed an issue in the following scenario:
1. Bridges A and B have participants in the same conference
1. All the participants in that conference on bridge A leave
1. Bridge B is told that the remote participants are gone, but isn't told that relay (bridge A) is no longer in the call, so it continues forwarding packets there
Part of the reason the above flow fails, is that in `BridgeSession#removeSourcesFromOcto`, the relays we include in the colibri come from the `OctoParticipant`, but the 'removed' relay has not yet been removed from the participant at that point.
This PR adds a call to `updateColibriOctoChannels` to `BridgeSession#setRelays`.  This is where the relays in the `OctoParticipant` are updated, so doing an update at this point does include the proper set of relays.
=> update the relays on the bridge in BridgeSession#setRelays

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/bridge/Bridge.java, src/main/java/org/jitsi/jicofo/bridge/BridgeMucDetector.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java
This relies on the work in https://github.com/jitsi/jitsi-videobridge/pull/1268 and integrates the JVB API with Jicofo.
In this first version, Jicofo looks for values present in JVB's presence that advertise support for the new JVB API.  If those are present, all requests are sent via the JVB API, if not then it falls back to the existing XMPP connection.
Still considering this a WIP, as we may want some other tweaks before merging this (even if we didn't enable it in JVB yet).
=> Integrate JVB API

src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java, src/main/java/org/jitsi/jicofo/OctoChannelAllocator.java, src/main/java/org/jitsi/jicofo/ParticipantChannelAllocator.java, src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java, src/test/java/org/jitsi/jicofo/ColibriTest.java, src/test/java/org/jitsi/jicofo/ColibriThreadingTest.java
A setting to improve the audio quality is frequently requested in the community forum. While it is already possible to disable audio processing and to enable stereo through `config.js` options, there is currently no way to adjust the actual bitrate thats produced by the Opus encoder. This PR provides a way to influence the audio bitrate through a `config.js` option.
While this PR provides a workaround that allows to control the used audio bitrate to some degree, I am by no means certain that this is the way to go. There may be more efficient ways to achieve this and there could even be ways unknown to me that provide more fine grained control over the mode used by the Opus encoder. The main intention behind this PR is therefore to start a discussion about how an option for improved audio …
=> Add option to improve audio quality

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/bridge/Bridge.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java
This reverts commit c1ad0440affb12b09900a5dd97e536343d350123.
We've decided to go a different direction with the JVB API and postpone a transport change until later in the evolution of colibri. This PR removes the integration of the jvb-api-client code in jicofo.
=> Revert "Integrate JVB API (#538)"

src/main/java/org/jitsi/impl/protocol/xmpp/OpSetSimpleCapsImpl.java, src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java
Use getter to fetch the current XMPP connection. This fixes
an issue where the connection is always null if it wasn't
available on bundle startup.
Also reduces logging level on discovery error to warning.
=> fix(JvbDoctor): connection null on bad timing

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/DefaultJingleRequestHandler.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/LipSyncHack.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/JingleRequestHandler.java, src/main/java/org/jitsi/protocol/xmpp/OperationSetJingle.java, src/test/java/mock/muc/MockRoomMember.java, src/test/java/org/jitsi/jicofo/ParticipantTest.java
Implements 'session-terminate' which allows the clients to end the session. If there's the restart attribute set to true in the <bridge-session> extension, then Jicofo will start a new session after tearing down the existing one.
Adds rate limiting on the restart requests to prevent abuse and/or client bugs. There must be at least 10 second gap between the requests and no more than 3 requests are allowed in the last minute.
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/30
=> feat: add support for session-terminate

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java
Adds 'terminate-restart' to the list of features supported by Jicofo.
The client needs to to be able to check if Jicofo supports it, because
there's no going back from doing the 'session-terminate' otherwise.
=> feat: advertise support for session restart

doc/health-checks.md
Fixed same typo like [here](https://github.com/jitsi/jitsi-videobridge/pull/867/files) and added the information behind which port I can find the REST API to access the health checks.
I was looking a while to find the right place in the code.
=> docs: fix typo and add port info for health checks

src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java, src/main/java/org/jitsi/jicofo/xmpp/BaseBrewery.java, src/test/kotlin/org/jitsi/jicofo/recording/jibri/JibriDetectorTest.kt, src/test/kotlin/org/jitsi/jicofo/recording/jibri/JibriSessionTest.kt
If Jicofo encounters a Jibri error on the initial request, it throws and fails immediately because the assumption was that anything in the instances list should be present.  We've recently run into errors where a Jibri in a strange state is at the front of the queue and fails repeatedly: this means Jicofo fails each time but, for the next request, tries the same Jibri again.  Because we don't know how permanent the error state is for this Jibri, this PR adds an API to denote that a JibriSession encountered a transient error with the Jibri, which moves it to the back of the line.  It also retries in this case, similar to the retries we perform when getting an error response back from Jibri.
=> Handle Jibri errors on initial request

src/main/java/org/jitsi/jicofo/bridge/BridgeSelectionStrategy.java
Note that the adjusted stress (taking new endpoints into account) is printed by the bridge's `toString()` method so this clarifies why the two values are different.
=> Clarify and enhance bridge selection log.

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
JVB parses the GID using `gid = Long.parseLong(gidStr, 16);` (VideobridgeShim.java)
https://github.com/jitsi/jicofo/issues/606
=> Send the HEX GID to JVB

src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java
I'm working on Jibri to make it supporting recording multi rooms parallelly. The jibri need the session ID to decide which room recording should stop.
=> Jibri send 'stopRequst' with session ID.

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
This attempts to fix is the following case of moving participants to another bridge after a failure:
Endpoints A and B on jvb1, endpoints C and D on jvb2. Kill jvb1. Endpoints A and B are moved to jvb3. The following happens:
- Video between C and D continues to work, but not for any other endpoints.
- The jicofo logs seem normal — it sees jvb1 go away, allocates channels on a new bridge, sends transport-replace, receives transport-accept.
- On jvb2 things seem normal — remove relay for jvb1, add relay for jvb3.
- jvb3 receives a conference request and creates OctoEndpoint-s for endpoints A and B. Then it replaces that with local Endpoint instances and gathers candidates. While in that state, jvb3 spams the logs with `Received a message with an unexpected type: …
=> Octo user migration fixes

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/test/java/mock/muc/MockMultiUserChat.java
Web and mobile clients can use that to quickly resolve features supported in the conference, rather than doing the expensive disco-info.
=> feat: Adds conference property in the presence for terminate-restart.

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java
In this case removing the extension BridgeNotAvailablePacketExt from presence on every onColibriConferenceAllocated, was resending last presence.
=> fix: Skip sending duplicate identical presences.

src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSipGateway.java, src/test/kotlin/org/jitsi/jicofo/recording/jibri/JibriSessionTest.kt
This PR aims to address the following issue:
* Call A starts a recording, Jibri 1 is selected
* Call B starts a recording, Jibri 1 was selected (Jicofo didn't see it as busy yet)
* Call A's JibriSession gets a pending response
* Call B's JibriSession gets a busy response
* Jicofo treats any response that's not pending to a Jibri request as an error, so we now consider Jibri 1 in an error state
* Jicofo removes and re-adds Jibri 1 to the MUC in order to move it to the back of the line
* Call A's JibriSession sees the Jibri leave the MUC, so sends an error to the client (thinking Jibri went away)
The fix was to not treat the busy response as a transient error.
=> Fix handling of Jibri busy response

src/main/java/org/jitsi/jicofo/bridge/BridgeSelector.java
When participant joins and a bridge goes down at the same time we can get this:
Found one Java-level deadlock:
=============================
"Smack-Single Threaded Executor 1 (0)":
waiting to lock monitor 0x00007f4a580f3538 (object 0x00000006c28d1af8, a java.util.LinkedList),
which is held by "Smack-Single Threaded Executor 1 (1)"
"Smack-Single Threaded Executor 1 (1)":
waiting to lock monitor 0x00007f4a3801c0a8 (object 0x00000006c01c4ae0, a org.jitsi.jicofo.bridge.BridgeSelector),
which is held by "Smack-Single Threaded Executor 1 (0)"
Java stack information for the threads listed above:
===================================================
"Smack-Single Threaded Executor 1 (0)":
at org.jitsi.jicofo.JitsiMeetConferenceImpl.onMultipleBridgesDown(JitsiMeetConferenceImpl.java:2372)
- waiting …
=> fix: Fix deadlock in bridge selector.

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/xmpp/IqHandler.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java
This change adds the ability for a moderator to deactivate the camera of other participants. The implementation uses the same approach that was implemented to mute audio of other participants.
This feature consists of multiple PRs:
- https://github.com/jitsi/jitsi-media-transform/pull/329
- https://github.com/jitsi/jitsi-videobridge/pull/1570
- https://github.com/jitsi/jitsi-xmpp-extensions/pull/37
- https://github.com/jitsi/jicofo/pull/695
- https://github.com/jitsi/lib-jitsi-meet/pull/1496
- https://github.com/jitsi/jitsi-meet/pull/8630
=> Added mute video moderation feature

pom.xml, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/kotlin/org/jitsi/impl/protocol/xmpp/JingleStats.kt, src/main/kotlin/org/jitsi/jicofo/JicofoServices.kt
Do not send source-add for injected SSRCs because Octo currently requires each endpoint to have at least one associated SSRC, jicofo injects a dummy audio SSRC for endpoints that do not advertise any SSRCs of their own. This makes sure that the dummy SSRCs are kept only for Octo and not propagated to other endpoints.
=>  @bgrozev fix: Do not send source-add for injected SSRCs. 

debian/postinst
((users doubleclick a host name and paste result in the installer)
how to reproduce ? install in a clean instance and add a space before the host name
Result:
https://community.jitsi.org/t/installation-problem-on-ubuntu-20-04-2-lts/94776
see also https://github.com/jitsi/jitsi-meet/pull/8728
=> handles spaces around hostname

src/main/java/org/jitsi/jicofo/xmpp/IqHandler.java
When running with the recent refactor, I got the following in the log and was unable to dial out.
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method org.jitsi.jicofo.jigasi.JigasiDetector.selectSipJigasi, parameter exclude
=> Make sure exclude is not null

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/xmpp/IqHandler.java
I started doing it, but then I found that there are 3 more places like this that will need similar changes and those are the grantOwner, start Jibri and start transcriber.
Or we can change so that we have a pool of threads executing these tasks ... WDYT?
People were asking whether recording started taking a little bit longer, I guess the same is happening ...
=> Fixes blocking receiver thread

src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java
Avoid having: `<content name='video'><description media='video' xmlns='urn:xmpp:jingle:apps:rtp:1'/></content>`
=> fix: Skips sending empty video content on source-add.

src/main/java/org/jitsi/jicofo/health/JicofoHealthChecker.java
WARNING: [15] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[focus@auth.jitsi.net/focus] (0) clos
ed with error
java.lang.NullPointerException
at org.jitsi.jicofo.health.JicofoHealthChecker.lambda$pingClientConnection$1(JicofoHealthChecker.java:204)
=> fix: Adds a nullcheck fixes NPE.

src/main/kotlin/org/jitsi/jicofo/xmpp/JigasiIqHandler.kt, src/main/kotlin/org/jitsi/jicofo/xmpp/XmppServices.kt, src/test/kotlin/org/jitsi/jicofo/xmpp/jigasi/JigasiIqHandlerTest.kt
I don't know what I'm doing - all I know is that jigasi couldn't find any conference given it's using EmptyConferenceStore to do lookup (log shows "rejected ... non-existent conference").
The patch appears to work fine for me. Please advice.
=> Fix jigasi iq handler

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/kotlin/org/jitsi/jicofo/JicofoServices.kt, src/main/kotlin/org/jitsi/jicofo/jigasi/JigasiConfig.kt, src/main/kotlin/org/jitsi/jicofo/xmpp/XmppServices.kt
When Jicofo is configured to use the service XMPP connection for Jigasi, it still accesses the Jigasi brewery MUC using the client connection. This patch fixes it to use the connection selected in jicofo.conf for jigasi.
=> Use the service connection (if configured) for the Jigasi detector

src/main/kotlin/org/jitsi/jicofo/util/QueueExecutor.kt
This is a partial fix. Exposing queue stats, logging when items are dropped, and potentially using an unbounded queue will follow in a separate PR.
=> fix: Increase the conference queue executor queue size.

pom.xml
Work around bug in jxmpp 1.0.1 parsing a JID localpart containing an @ character.
=> Fix: bump jitsi-xmpp-extensions.

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java
(See commit 3f570999 for an explanation of the race.)
=> Hack to work around a race in Smack.

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/jicofo/conference/BridgeSession.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/jigasi/TranscriberManager.java, src/main/kotlin/org/jitsi/jicofo/xmpp/AvModerationHandler.kt, src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt, src/main/kotlin/org/jitsi/jicofo/xmpp/JigasiIqHandler.kt, src/main/kotlin/org/jitsi/jicofo/xmpp/MuteIqHandler.kt
Submit returns a Future instance which when unhandled will cause any exceptions inside the Runnable body to be swallowed.
=> ref: replace submit with execute

src/main/java/org/jitsi/impl/protocol/xmpp/ChatMemberImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoom.java, src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomMember.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/kotlin/org/jitsi/jicofo/ConferenceConfig.kt, src/main/kotlin/org/jitsi/jicofo/conference/source/EndpointSourceSet.kt, src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomListener.kt, src/main/resources/reference.conf, src/test/java/mock/muc/MockChatRoom.java, src/test/java/mock/muc/MockRoomMember.java
Keep track of the number of video senders in a conference, that is, the number of participants who have unmuted their video source. When the limit is reached, return an error if another participant attempts to unmute their video.
This is an attempt to avoid issues that may arise from the storm of signaling that may occur when a large number of participants unmute at the same time.
=> Limit video senders

src/main/java/org/jitsi/jicofo/codec/JingleOfferFactory.java
Opus RED is now enabled on Chrome M96, but it requires this extra FMTP line.
=> Add RFC 2198 fmtp line for Opus RED

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoom.java, src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/test/java/mock/muc/MockChatRoom.java
Emitting async was necessary in order to offload work from Smack's
single threaded executor. This is no longer necessary with Smack 4.4.4
as it uses a cached pool (segmented by MUC).
Processing presence from smack sync, but emitting async can lead to the
number of chat room members being out of sync.
=> Fire ChatRoom events sync

src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java
Check senders limit prior to adding them to the map.
=> Don't leave rejected sources in conferenceSources map.

src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/kotlin/org/jitsi/jicofo/conference/colibri/ColibriSessionManager.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v1/ColibriV1SessionManager.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Colibri2Session.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt
- fix: Remove sources when a participant leaved regardless of the presense of a jingle session.
- fix: Remove sources from octo  when a participant leaves.
=> Fix removing sources for octo

src/main/java/org/jitsi/jicofo/bridge/Bridge.java
As reported by @JonathanLennox calculating
Duration.between(Instance.MIN, X) is slow because Instance.Min isn't
representable as nanoseconds.
=> opt: Optimize isOperational

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoom.java, src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/conference/Participant.java, src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java, src/main/java/org/jitsi/jicofo/lipsynchack/LipSyncHack.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/kotlin/org/jitsi/jicofo/ConferenceConfig.kt, src/main/kotlin/org/jitsi/jicofo/JicofoConfig.kt, src/main/kotlin/org/jitsi/jicofo/auth/AuthConfig.kt, src/main/kotlin/org/jitsi/jicofo/bridge/BridgeConfig.kt, src/main/kotlin/org/jitsi/jicofo/bridge/BridgeSelector.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/ColibriConfig.kt, src/main/kotlin/org/jitsi/jicofo/health/HealthConfig.kt, src/main/kotlin/org/jitsi/jicofo/jibri/BaseJibri.kt, src/main/kotlin/org/jitsi/jicofo/jibri/JibriConfig.kt, src/main/kotlin/org/jitsi/jicofo/jigasi/JigasiConfig.kt, src/main/kotlin/org/jitsi/jicofo/xmpp/XmppConfig.kt, src/test/java/mock/muc/MockChatRoom.java, src/test/java/mock/muc/MockMucShare.java, src/test/kotlin/org/jitsi/jicofo/ConferenceConfigTest.kt, src/test/kotlin/org/jitsi/jicofo/auth/AuthConfigTest.kt
- opt: Use a map for participants, linear search is slow for large conferences.
- opt: Do not search the members map linearly, cleanup
- ref: Use a static instance for colibri config.
- ref: Use a static instance for AuthConfig.
- ref: Use a static instance for BridgeConfig.
- ref: Make the HealthConfig constructor private.
- ref: Use a static instance for ConferenceConfig.
- ref: Make the JigasiConfig constructor private.
- ref: Make the XmppConfig constructor private.
- ref: Make the JicofoConfig constrructor private.
- ref: Make the JibriConfig constructor private.
=> Performance optimizations

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProviderImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/log/PacketDebugger.java, src/main/kotlin/org/jitsi/impl/protocol/xmpp/XmppProvider.kt, src/main/kotlin/org/jitsi/jicofo/JicofoServices.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Colibri2Session.kt, src/test/java/mock/MockXmppProvider.java
- log: Log expiring relayed endpoints at debug.
- fix: Only insert a debugger into smack when debug logging is enabled.
- feat: Remove xmpp "packet stats".
- feat: Use the connection name when logging XMPP traffic
=> Logging adjustments

src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java
...for injected audio sources.
It is required, because of this constraint:
https://github.com/jitsi/jitsi-videobridge/pull/1793/files#diff-9d9ade953a28940dd8dc6ad1a9378bacde2eab16400e03959d3bac1cb539f46fL295
I think it's okay to generate the source-name here, because it's Jicofo who's in charge of signaling this one and my understanding is that it's removed eventually.
=> fix(multi-stream): generate source name

src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Colibri2Session.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt
- fix: Just log a message when ParticipantInfo is missing.
- fix: Do not log exception when a JVB is removed while a health check is running.
- fix: Set the rtcstats/callstats flag for colibri2.
=> Colibri2 fixes

src/main/java/org/jitsi/jicofo/bridge/Bridge.java, src/main/kotlin/org/jitsi/jicofo/bridge/BridgeSelector.kt, src/test/java/mock/util/TestConference.java, src/test/kotlin/org/jitsi/jicofo/bridge/BridgeReleaseTest.kt, src/test/kotlin/org/jitsi/jicofo/bridge/BridgeSelectorTest.kt, src/test/kotlin/org/jitsi/jicofo/bridge/BridgeTest.kt, src/test/kotlin/org/jitsi/jicofo/bridge/RegionBasedSelectionTest.kt, src/test/kotlin/org/jitsi/jicofo/util/ConfigHelpers.kt
Prefer active bridges to draining ones.
Fail selection if pinned to a version different than the
one the conference is already using.
=> Use drain mode flag in bridge selection.

src/main/kotlin/org/jitsi/jicofo/bridge/BridgeSelector.kt, src/test/kotlin/org/jitsi/jicofo/bridge/BridgeSelectorTest.kt
Match all requirements before filtering by preferences.
Fix warning text when there are no bridges at all.
=> Tweak bridge selection.

src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/conference/Participant.java, src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java, src/main/kotlin/org/jitsi/jicofo/conference/colibri/ColibriSessionManager.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Colibri2Session.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt, src/test/kotlin/org/jitsi/jicofo/conference/ParticipantInviteRunnableTest.kt
- fix: Set forceMute state with the initial colibri allocate request and jingle offer.
- fix: Send a single coolibri message for force-mute, do not block for a response.
Incidentally, this fixes a race condition between terminateParticipant() and muteAllParticipants() which throws an exception when trying to mute a participant that has been removed.
=> Mute fixes

src/main/java/org/jitsi/jicofo/auth/ShibbolethAuthAuthority.java, src/main/java/org/jitsi/jicofo/auth/rest/ShibbolethLogin.java, src/main/java/org/jitsi/jicofo/rest/Application.java
as part of the org.jitsi.jicofo.rest package. This was a harmless bug,
resulting in 5XX instead of 404 when serving /login when shibboleth is
disabled.
=> fix: Prevent jetty from trying to register ShibbolethLogin

src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java, src/main/kotlin/org/jitsi/jicofo/bridge/BridgeSelector.kt
- log: Set initial fields before logging.
- Use healthCheckFailed when a bridge reports healthy (instead of handling as a timeout).
=> Fail (instead of timeuot) jvb health check when jvb reports unhealthy

src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt
When a session is removed the participantsBySession map is left with an
entry for the session (with an empty list of participants). This results
in the bridge being passed to BridgeSelector indefinitely.
In particular, this causes a serious problem when the bridge does not
have a relay, because BridgeSelector returns it back immediately, even
if the instance has disconnected.
=> fix: Fix broken Colibri2SessionManager state.

src/main/kotlin/org/jitsi/jicofo/TaskPools.kt
It is unlimited, so it will grow as needed. There's no need to
keep 200 threads alive at all time.
=> fix: Reduce the core size of the scheduled pool to 3.

src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt
The following deadlock was observed when ColibriV2SessionManager fails
to allocate channels and calls into bridgeRemoved in the same thread
while holding syncRoot:
BridgeSelector-AsyncEventEmitterpool-5-thread-1  Blocked Thread ID: 56
org.jitsi.jicofo.conference.colibri.v2.ColibriV2SessionManager.updateParticipant(Participant, IceUdpTransportPacketExtension, ConferenceSourceMap, boolean) ColibriV2SessionManager.kt:441
org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.removeSources(Participant, EndpointSourceSet, boolean, boolean) JitsiMeetConferenceImpl.java:1360
org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.reInviteParticipants(Collection) JitsiMeetConferenceImpl.java:1781
org.jitsi.jicofo.conference.JitsiMeetConferenceImpl.reInviteParticipantsById(List) …
=> fix: Fix a deadlock when CSM calls bridgeRemoved.

src/main/kotlin/org/jitsi/jicofo/codec/CodecUtil.kt
Currently when RED is being used as FEC we also signal the usage of Opus inband FEC. Running these two FECs algorithms together just wastes bandwidth for little to no gain. Since the results for RED for heavier packet loss is better compared to Opus FEC, this PR turns off Opus FEC when RED is in use.
=> Turn off Opus inband FEC when RED is in use

src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt
The API is called whenever any bridge goes down, regardless if it is
used by the conference.
=> log: Only log when a session is removed.

src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt
Prior to #925 a bridge with no relay-id configured leaving the MUC would result in it being selected over and over again. 
This PR limits the consequences if a similar situation happens again.
=> fix: Do not re-invite participants when the selected bridge is unavailable.

src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Colibri2Session.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt
- feat: Use a "expire conference" message instead of expiring individual endpoints.
- fix: Expire conference and re-invite participants on colibri conference-exists error.
- squash: Fix whitespace.
=> Use "expire conference" instead of expiring individual endpoints

src/main/kotlin/org/jitsi/jicofo/bridge/Bridge.kt, src/main/kotlin/org/jitsi/jicofo/bridge/BridgeSelector.kt, src/test/kotlin/org/jitsi/jicofo/bridge/BridgeSelectorTest.kt
- fix: Update newEndpointsRate when a Bridge is selected (fixes #943).
- test: Add test for recently added endpoint affecting stress.
=> Fix stress accounting for recently added endpoints

src/main/java/org/jitsi/jicofo/bridge/RegionBasedBridgeSelectionStrategy.java, src/test/kotlin/org/jitsi/jicofo/bridge/BridgeSelectionStrategyTest.kt
- test: Set local-region for selection tests.
- test: Use local region, fix expected selection.
- fix: Fall back to local region if there are no bridge in a participant's region group.
=> Add selection tests, fallback to local region

pom.xml, src/main/kotlin/org/jitsi/jicofo/bridge/Bridge.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt
- fix: Set the graceful-shutdown flag when we receive a graceful-shutdown error from jvb.
- Recognize colibri2 graceful-shutdown errors.
=> Fix graceful-shutdown handling

pom.xml
jitsi/jicoco#177
jitsi/jicoco#179
jitsi/jicoco#176
=> chore: Update jicoco

jicofo-common/src/main/java/org/jitsi/impl/protocol/xmpp/AbstractXmppProvider.java
Smack calls the reconnect callback while holding the XMPPConnection
lock. Run our own listeners in an IO thread in case on of them blocks
(as we've observed happening)
=> fix: Fire registratinChanged in IO pool.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/conference/source/Source.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Colibri2Session.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Extensions.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/java/org/jitsi/jicofo/rest/Debug.java, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/MuteIqHandler.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/Smack.kt
- Fix/supress warnings.
- fix: Set XML parsing settings.
- ref: Reuse ParticipantInfo.toEndpoint.
- fix: Fix ConcurrentModificationException when bridge count changes.
=> Fix ConcurrentModificationException.

debian/init.d, debian/postinst, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppConfig.kt, jicofo-selector/src/main/resources/reference.conf, jicofo/src/main/java/org/jitsi/jicofo/Main.java, resources/jicofo.bat, resources/jicofo.sh
This needs more testing. But the idea is that command line arguments are no longer used. All options that used command line arguments are now set in jicofo.conf instead, and `postinst` takes care of moving things from `/etc/jitsi/jicofo/config` to `jicofo.conf`.
- debian: Only pass command line params if the options are defined.
- fix: Read xmpp-domain from jicofo.conf.
- debian: Move xmpp config from "config" to jicofo.conf.
- debian: Do not pass /etc/jitsi/jicofo/config values as command line arguments.
- ref: Do not read command line arguments (use jicofo.conf instead).
- Add docs to reference.conf.
=> Move XMPP config to jicofo.conf

jicofo/src/main/kotlin/org/jitsi/jicofo/jibri/JibriRecorder.kt
- fix: Set JibriRecorder.jibriSession prioor to running start().
- fix: Run JibriSession.stop() in an IO thread as it might block.
=> Fix stopping jibri sessions

debian/postinst
- Use only alpha-numerics when generating passwords.
- fix: Quote strings in hocon.
=> Fix updating jicofo.conf

jicofo/src/main/kotlin/org/jitsi/jicofo/conference/Participant.kt
i have problem which is https://community.jitsi.org/t/sometimes-source-add-is-not-propagated-properly/119046
test version : stable/jitsi-meet_7648
when new participants come into meeting, some of participants could hear, but the others couldn't hear
i think it's data racing within sourcesingaling reset, with synchronized version, it's never occured.
could you please reivew it?
=> fix: update sourcesignaling when received simultaneously source-add

jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java
A reason must be specified otherwise an exception is thrown and the reinvite doesn't happen:
```
Jicofo 2022-12-05 12:59:44.822 INFO: [32] [room=saghul8@conference.alpha.jitsi.net meeting_id=86b66da8-47ac-4107-82db-032d73af282c] JitsiMeetConferenceImpl.terminateParticipant#824: Terminating 94892c10, reason: null, send session-terminate: false
Jicofo 2022-12-05 12:59:44.823 WARNING: [32] org.jivesoftware.smack.AbstractXMPPConnection$1$1.uncaughtException: Thread[Smack Cached Executor,5,main] encountered uncaught exception
java.lang.NullPointerException: Parameter specified as non-null is null: method org.jitsi.jicofo.xmpp.jingle.JingleSession.terminate, parameter reason
at org.jitsi.jicofo.xmpp.jingle.JingleSession.terminate(JingleSession.kt)
at …
```
=> fix: gracefully handle receiving a session-terminate with reinvite

jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java
Jigasi doesn't advertise support for source-names, but it's unaffected
by them. The stats are indented to indicate if there are clients out there that
still need the non-source-name mode which is planned to be removed. Same
for receiving multiple streams.
=> Exclude jigasi from stats for "no source name" stats

jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriV2SessionManager.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Exceptions.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java
Added conference expiration and then re-request allocation for endpoint when allocation is failed with error of already existed conference which can happen after jicofo restart.
Hi guys, added the code which should handle the case when jicofo after restart tries to re-create endpoints and have error from jvb that such conferences already existed which prevent jicofo to restore the existed before conferences.
=> ref(endpoint-allocation): add conference expiration and re-request allocation upon already existed conference error

jicofo/src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/Participant.kt
JingleSessions register with JingleIqHandler which saves a weak
reference and there are no other references to the object until
the session is accepted and saved as Participant.jingleSession. If
the weak reference expires before session-accept is received the
session fails to establish.
This is a quick and dirty fix, a proper solution will follow later.
=> fix: Temporary fix for JingleSession-s being GC too early

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/jingle/JingleSession.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/Participant.kt
Participant.jingleSession is now set when we initially create the
JingleSession instance and send a session-initiate IQ. Whether the
session is active is kept track of using JingleSession.state.
=> fix: Fix JingleSession handling.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/codec/CodecConfig.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Colibri2Session.kt, jicofo-selector/src/main/resources/reference.conf, jicofo/src/main/java/org/jitsi/jicofo/codec/JingleOfferFactory.java, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/ConferenceUtil.kt, pom.xml
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/90.
=> Send extmap-allow-mixed in Jingle and Colibri2, if configured.

jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppServices.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/ConferenceIqHandlerTest.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/auth/ShibbolethAuthenticationAuthorityTest.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/auth/XMPPDomainAuthAuthorityTest.kt
- feat: Return ready=false when the MUC is not joined (regardless of whether authentication is enabled).
- ref: Remove isFocusAnonymous (unused now).
=> feat: Return ready=false when the MUC is not joined (regardless of whether authentication is enabled).

jicofo/src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java
With SCTP enabled we log "Failed to convert ContentPacketExtension to Media" at WARN when we create an offer.
=> Do not try to parse the "data" content as Media.

jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Colibri2Session.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriSessionManager.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriV2SessionManager.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java
Added functionality to re-invite participant when UNKNOWN_ENDPOINT Colibri2Error happened instead of recreating the whole bridge and re-invite all participants. It can happen when endpoint is expired on jvb but jicofo tries to send update about this endpoint and gets error back.
Added this change as part of https://github.com/jitsi/jicofo/issues/1047
=> ref(colibri2 session participant re-invite): re-invite user on unknown endpoint error

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/Features.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoom.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt, jicofo-selector/src/main/resources/reference.conf, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConference.java, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/FocusManager.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/ConferenceMetrics.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/ConferenceUtil.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/visitors/VisitorsConfig.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/VisitorsManager.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppServices.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/ConferenceIqHandlerTest.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/auth/ShibbolethAuthenticationAuthorityTest.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/auth/XMPPDomainAuthAuthorityTest.kt
- Send connect-vnode and disconnect-vnode to the visitors component.
- Check for visitors-version in conference-request.
- tmp
- fix: Fix generating visitor MUC JID when the room uses a tenant.
- fix: Fix counting visitors, randomize vnode selection.
- Add a Feature for visitors.
- Add metrics for visitors.
- Fix lint errors.
- squash: Fix visitor count.
- squash: Remove extra log.
- Fix visitor count.
=> Visitor updates

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomMember.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomMemberImpl.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/Smack.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/jibri/JibriDetectorTest.kt
- Recognize chat room members as jigasi transcribers.
- Exclude jibri and transcribers from participant count for visitor redirection.
=> Recognize and exclude transcriber/jibri from participant count for visitor redirection

jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java
When a non-visitor leaves, the MUC occupant is removed, leading to
getRole() falsely returning VISITOR, and visitorRemoved() being run.
=> fix: Temporary fix for counting visitors.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/codec/CodecConfig.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/codec/CodecUtil.kt, jicofo-selector/src/main/resources/reference.conf, jicofo/src/test/kotlin/org/jitsi/jicofo/CodecConfigTest.kt
It has never been used with jicofo/jitsi-meet as far as we know, and it was removed in Chrome 110 as pointed out here:
https://community.jitsi.org/t/remove-the-support-for-isac/122815/2
=> Remove iSAC from the offer.

jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/test/kotlin/org/jitsi/jicofo/mock/MockChatRoom.kt
- fix: Run feature discovery in a separate thread.
- fix: Try to avoid sending unnecessary disco#info
=> Fix feature discovery blocking a smack thread.

jicofo-common/src/main/java/org/jitsi/jicofo/xmpp/BaseBrewery.java, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoom.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConference.java, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConfigurationChangeHandler.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppServices.kt
- Revert "Set the meetingId for the visitors room to that of the main room. (#1072)"
- Set the meetingId of visitor ChatRooms locally.
- feat: Reload MUC config if changed, read lobbyEnabled, do not use visitors when lobby enabled.
=> Do not use visitors when lobby enabled.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomMemberImpl.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/Participant.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/util/RateLimitedStat.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/conference/ParticipantInviteRunnableTest.kt
Iterating over participant lists causes quadratic behavior when adding large numbers of visitors to a conference.
Instead, keep counts of the relevant values in parallel with the maps.
=> Avoid counting participants

jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt
Does not redirect jibri to the visitor nodes.
=> feat: Skip redirecting to vnodes any trusted domains.

jicofo-selector/src/main/resources/reference.conf, jicofo/src/main/kotlin/org/jitsi/jicofo/ConferenceConfig.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/Participant.kt
- Make restart request rate limits configurable.
- Relax restart request rate limits.
=> Relax the restart request limits

jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt
This reverts commit e05f8dab. Jibri now reports that visitors are not supported and this is not needed.
=> Revert "feat: Skip redirecting to vnodes any trusted domains."

jicofo-common/src/main/java/org/jitsi/impl/protocol/xmpp/log/PacketDebugger.java, jicofo-common/src/main/java/org/jitsi/jicofo/xmpp/BaseBrewery.java, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/Util.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/jingle/JingleSession.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt, jicofo-selector/src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Colibri2Session.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriV2SessionManager.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java, jicofo/src/main/java/org/jitsi/jicofo/jibri/JibriSession.java, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/Participant.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/jibri/BaseJibri.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/jibri/JibriRecorder.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/jibri/JibriSipGateway.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/rest/ConferenceRequest.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/AuthenticationIqHandler.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/JibriIqHandler.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/JigasiIqHandler.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/MuteIqHandler.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/VisitorsManager.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/auth/XMPPDomainAuthAuthorityTest.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/conference/ConferenceTest.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/xmpp/jigasi/JigasiIqHandlerTest.kt, pom.xml
- chore: Update jitsi-xmpp-extensions.
- log: Remove System.err logs.
- fix: Avoid using XmlStringBuilder.toString.
=> avoid xmlstring builder toString

jicofo/src/main/kotlin/org/jitsi/jicofo/rest/ConferenceRequest.kt
Jetty doesn't recognize that the kotlin param can't be null which
results in a NPE and response 500. Return 400 without polluting the logs
instead.
=> fix: Fix NPE when a conference request has no payload

jicofo-selector/src/main/resources/reference.conf
JVB has supported it for a while.
=> Default extmap-allow-mixed to on.

jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriSessionManager.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Extensions.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ParticipantInfo.kt, jicofo-selector/src/main/resources/reference.conf, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java, jicofo/src/main/kotlin/org/jitsi/jicofo/ConferenceConfig.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/FocusManager.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/ConferenceMetrics.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/Participant.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/SourceSignaling.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/conference/source/SourceSignalingTest.kt
- ref: Remove backward compatibility with endpoints with no source name support.
- Remove multi stream backward compat code.
=> Remove backward compat for source names and multi-stream

jicofo-common/src/main/kotlin/org/jitsi/jicofo/codec/CodecUtil.kt
Reported by @zhing https://community.jitsi.org/t/header-extension-parse-failed-in-jicofo/129619
=> Fix the ID of the RID extension.

jicofo-common/pom.xml, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoom.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomListener.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/RoomMetadata.kt, jicofo-common/src/test/kotlin/org/jitsi/jicofo/xmpp/muc/RoomMetadataTest.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/java/org/jitsi/jicofo/jigasi/TranscriberManager.java
Read room_metadata from the MUC config form, and enable transcription if
it is requested.
=> feat: Enable transcription based on MUC config form

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomMember.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomMemberImpl.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/util/PreferenceAggregator.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/Smack.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/jibri/JibriDetectorTest.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/util/PreferenceAggregatorTest.kt, pom.xml
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/104.
=> Monitor visitors' codec lists, and aggregate them into a conference property.

debian/control
Allows for running with Java 17 without any additional install.
=> Update Java Debian dependencies

jicofo-selector/src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java
Scheduling at a fixed rate leads to IO threads building up when a bridge
becomes unresponsibe and the duration of health checks becomes longer
than the health check interval.
=> fix: Fix scheduling jvb health checks.

jicofo-selector/src/main/resources/reference.conf, jicofo/src/main/kotlin/org/jitsi/jicofo/visitors/VisitorsConfig.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt
=> feat(visitors): Adds flag to enable live room feature.

jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/JigasiIqHandler.kt
Note it's just a precaution, prosody already verifies it.
=> feat: Verify the rayo JvbRoomName header if it exists.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt
Generate left/kicked events internally. In the future we want different
handling based on content of the presence which we can't do with
ParticipantStatusListener. Plus, we've had problems with them executing
in inconsistent order.
=> ref: Do not use ParticipantStatusListener

jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/test/kotlin/org/jitsi/jicofo/mock/MockChatRoom.kt
We keep around conferences when there is a breakout room. When a single participant is switching we first get participant left then breakout room is created, so we need to distinguish that the participant left is for joining breakout room.
=> fix(breakout-rooms): Fixes the case where a single participant switches to breakout room.

jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/VisitorsManager.kt
Use case is a single main participant and a visitor node. If jicofo leaves visitor room before disconnecting, the client will reload seeing jicofo leaving. If we disconnect first, we destroy the room with an appropriate message shown to visitors.
=> fix(visitors): Make sure we disconnect vnodes before leaving rooms.

jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/Bridge.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/BridgeConfig.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/BridgeSelectionStrategy.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/RegionBasedBridgeSelectionStrategy.kt, jicofo-selector/src/test/kotlin/org/jitsi/jicofo/bridge/BridgeConfigTest.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/jigasi/JigasiDetector.kt
- **feat: Add jigasi region to debug output**
- **feat: Support region groups for jigasi selection.**
- **ref: Remove unnecessary functions.**
=> feat: Support region groups for jigasi selection.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomMember.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomMemberImpl.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomRoleManager.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/jibri/JibriDetectorTest.kt
- **fix: Require trusted domain for jigasi.**
- **ref: Remove the "robot" flag.**
=> feat: Update jigasi detection 

jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Colibri2Session.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriV2SessionManager.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/ktor/Application.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/JigasiIqHandler.kt
Error responses to IQs may be parsed as a specific IQ type (e.g.
ConferenceModifyIQ) when they contain a child other than <error>. The
correct way to check for an error is with IQ.getError() instead of the
instance type.
=> fix: Handling of IQ error responses.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/Features.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/ConferenceMetrics.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt
- **log: Log when rtcstats is disabled.**
- **feat: Keep track of participants without support for start muted via room-metadata.**
=> Keep track of rtcstats disabled and start muted rmd support.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoom.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/auth/XMPPDomainAuthAuthorityTest.kt
- **fix: Only shortcut to the main room if the user is explicitly listed as a participant.**
- **Add more fields to debugState.**
=> Fix visitor redirection 
