jitsi/jicofo

resources/install/debian/postinst
Prevents error messages in postinst which result in errors on package install/upgrade.
=> Manipulates log files only if they exist.

src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/rest/Health.java
This way we know that Jicofo is ready to start conferences when returns 200.
=> Returns 500 to health check if JVB list was requested, but empty.

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/OpSetSimpleCapsImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolActivator.java, src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java, src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetServices.java, src/main/java/org/jitsi/jicofo/JvbDoctor.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/VersionBroadcaster.java, src/main/java/org/jitsi/jicofo/discovery/DiscoveryUtil.java, src/main/java/org/jitsi/jicofo/discovery/Version.java, src/main/java/org/jitsi/jicofo/log/EventFactory.java, src/main/java/org/jitsi/jicofo/osgi/JicofoBundleConfig.java, src/main/java/org/jitsi/jicofo/version/CurrentVersionImpl.java, src/test/java/mock/muc/MockRoomMember.java, src/test/java/org/jitsi/jicofo/JvbDoctorTest.java
This PR adds VersionBroadcaster which advertises the version of XMPP server, jicofo and videobridge in Jicofo MUC presence.
=> Version discovery

src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java
Fixes issue with recorderComponentJid not being cleared properly on status update coming from Jibri.
=> Jibri fixes

src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java
We should still check for Jibri availability instead of just setting the status to OFF
=> Fixes OFF status handling from Jibri

src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetRecording.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/recording/JvbRecorder.java
This PR moves out from JitsiMeetConference class all the code related to recording into separate class
=> Separate recorder

resources/install/debian/init.d, src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java
Renames adaptiveSimulcast to disableAdaptiveSimulcast.
=> Enable adaptive simulcast by default

src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetGlobalConfig.java, src/main/java/org/jitsi/jicofo/JitsiMeetRecording.java, src/main/java/org/jitsi/jicofo/recording/Recorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java
Just another round of Jibri improvements. Commit messages contain more details.
=> Jibri fixes2

pom.xml
Imports https://github.com/jitsi/jicofo/pull/31 from @champtar's fork into a jitsi/jicofo branch in order to enable automatic testing of further changes.
=> Update bcprov-jdk15on to 1.54

src/main/java/org/jitsi/jicofo/log/EventFactory.java
(use ```Dictionary<String, Object>``` for Event properties)
Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>
=> Remove some compiler warnings

lib/logging.properties, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java
Will log channel allocate response, also adds a hint to logging.properties
=> Log Colibri response

src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java
Gets rid of factory method shared by all media types(in order to avoid further extension of it's arguments
list).
=> Refactor JingleOfferFactory

src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java, src/test/java/org/jitsi/jicofo/BridgeSelectorTest.java
We use pubsub and discoinfo to configure the bridge.
=> Ignore the pre-configured bridge that comes from the client.

src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/test/java/mock/jvb/MockVideobridge.java, src/test/java/org/jitsi/jicofo/JvbDoctorTest.java, src/test/java/org/jitsi/jicofo/PubSubBridgeSelectorTest.java, src/test/java/org/jitsi/jicofo/util/ConferenceRoomListener.java
Bug fixes for ice-restart and implements conference restart, after we get bridge up event.
=> Jvb down restart

src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java
return statement was missing in the previous PR
=> Add missing return statement

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java, src/main/java/org/jitsi/jicofo/JitsiMeetGlobalConfig.java, src/main/java/org/jitsi/jicofo/LipSyncHack.java
Changes required for lip-sync tests
=> Lipsync tests

src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java
My Java is pretty rusty, but I think this is more or less idiomatic.
Retries are not implemented yet, but it should be relatively easy now that this is a separate method. Code reviews appreciated before I finish adding retries in case my Java is terrible or I'm completely barking up the wrong tree.
Sorry for all the import changes; the `*`'s were bothering me because I couldn't tell what package any identifiers came from. I can remove that from the diff before merge if it's not desired.
=> Refactor starting Jibris out into separate method

src/main/java/org/jitsi/jicofo/auth/AbstractAuthAuthority.java, src/main/java/org/jitsi/jicofo/auth/AuthBundleActivator.java, src/main/java/org/jitsi/jicofo/auth/ExternalJWTAuthority.java, src/main/java/org/jitsi/jicofo/auth/ShibbolethAuthAuthority.java, src/main/java/org/jitsi/jicofo/auth/XMPPDomainAuthAuthority.java
Integrates external login service which provides JWT token once the user authenticates.
=> Jwt login service

src/main/java/org/jitsi/jicofo/ChatRoomRoleAndPresence.java, src/main/java/org/jitsi/jicofo/JitsiMeetGlobalConfig.java
This PR makes some of the log messages less often or hides them completely as those are not interesting at all.
=> Less verbose logging

src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java
Do not mark JVB instance as "faulty" when it's the Jicofo who does the things wrong(JVB returns "bad request" error).
=> Bad request

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/OperationSetMeetToolsImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/extensions/BridgeNotAvailablePacketExt.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/test/java/mock/MockJitsiMeetTools.java
Makes sure that the "no bridge available" extension is removed from Jicofo presence.
=> Page reload overlay

pom.xml, src/main/java/org/jitsi/jicofo/xmpp/FocusComponent.java, src/test/java/org/jitsi/jicofo/ShutdownTest.java, src/test/java/org/jitsi/jicofo/XmppTest.java
Updates Jicoco in order to use the single thread packet processor. DO NOT MERGE YET(Jicoco is referenced by the SNAPSHOT version)
=> Process XMPP packets in order

src/main/java/org/jitsi/impl/protocol/xmpp/OpSetSubscriptionImpl.java, src/main/java/org/jitsi/impl/reservation/rest/RESTReservations.java, src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/ChatRoomRoleAndPresence.java, src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetServices.java, src/main/java/org/jitsi/jicofo/JvbDoctor.java, src/main/java/org/jitsi/jicofo/LipSyncHack.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/VersionBroadcaster.java, src/main/java/org/jitsi/jicofo/auth/AuthenticationSession.java, src/main/java/org/jitsi/jicofo/recording/Recorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriDetector.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/jicofo/rest/Health.java, src/main/java/org/jitsi/protocol/xmpp/JingleSession.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCGroup.java
Uses Objects.requireNonNull instead of Assert.notNull.
=> Minor clean-up: don't use Assert.notNull

resources/install/debian/control, resources/install/debian/po/POTFILES.in, resources/install/debian/po/templates.pot, resources/install/debian/postinst, resources/install/debian/templates
Please do not merge.
Work in progress decoupling jitsi-meet components. Introducing a new jitsi-meet meta package depending on particular component versions.
=> Updates debian packaging.

resources/collect-dump-logs.sh
check for and archive up the crash dumps from /var/crash if they exist for our user in the past 20 minutes
=> check for and archive up the crash dumps

src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/protocol/xmpp/util/MediaSSRCMap.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCSignaling.java
All video SSRCs have to be merged by the lipsync hack if simulcast is enabled.
=> Fix simulcast lipsync hack

src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java, src/test/java/mock/util/TestConference.java
The option got axed, there is nothing to handle now.
=> cleanup: remove code handling simulcast mode

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/OperationSetColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/JitsiMeetServices.java, src/main/java/org/jitsi/jicofo/event/BridgeEvent.java, src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java, src/main/java/org/jitsi/protocol/xmpp/util/ColibriConferenceIQUtil.java, src/test/java/mock/MockProtocolProvider.java, src/test/java/mock/MockProtocolProviderFactory.java, src/test/java/mock/xmpp/colibri/AllocThreadingTestColibriConference.java, src/test/java/mock/xmpp/colibri/MockColibriOpSet.java
Jicofo will try to estimate what is the current video stream count for each JVB based on the amount of channels it allocates/expires.
=> Video stream estimation

pom.xml, resources/mvn-exec.sh, src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java
Other than VP9 support, this also adds a payload type for H264 RTX.
=> Adds VP9 support.

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/impl/reservation/rest/RESTReservations.java, src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/BridgeState.java, src/main/java/org/jitsi/jicofo/ChannelAllocator.java, src/main/java/org/jitsi/jicofo/ComponentsDiscovery.java, src/main/java/org/jitsi/jicofo/FocusBundleActivator.java, src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetServices.java, src/main/java/org/jitsi/jicofo/Main.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/ProtocolProviderHandler.java, src/main/java/org/jitsi/jicofo/VersionBroadcaster.java, src/main/java/org/jitsi/jicofo/auth/AbstractAuthAuthority.java, src/main/java/org/jitsi/jicofo/discovery/DiscoveryUtil.java, src/main/java/org/jitsi/jicofo/xmpp/FocusComponent.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java, src/test/java/org/jitsi/jicofo/BridgeSelectorTest.java, src/test/java/org/jitsi/jicofo/PubSubBridgeSelectorTest.java
Extracts BridgeState to a separate file, adds synchronization, minor clean-up.
=> Refactoring and clean-up

src/main/java/org/jitsi/jicofo/BridgeSelector.java
BridgeSelectorTest calls select with null conference
=> fix(BridgeSelector): NPE when no participant is given

pom.xml, src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java, src/test/java/mock/media/MockMediaStream.java, src/test/java/mock/media/MockVideoMediaStream.java
Provides https://github.com/jitsi/libjitsi/pull/361
Depends https://github.com/jitsi/jitsi/pull/391/files
=> feat: Implements send-side bandwidth estimations.

src/main/java/org/jitsi/jicofo/SSRCValidator.java, src/main/java/org/jitsi/protocol/xmpp/util/MediaSourceGroupMap.java, src/main/java/org/jitsi/protocol/xmpp/util/MediaSourceMap.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCSignaling.java, src/main/java/org/jitsi/protocol/xmpp/util/SimulcastGrouping.java, src/main/java/org/jitsi/protocol/xmpp/util/SourceGroup.java, src/test/java/org/jitsi/jicofo/ParticipantTest.java
SSRCValidator will now check for MSID conflicts across SIM and FID groups.
=> feat(SSRCValidator): check for MSID conflicts

src/main/java/org/jitsi/jicofo/SSRCValidator.java, src/main/java/org/jitsi/protocol/xmpp/util/MediaSourceGroupMap.java, src/main/java/org/jitsi/protocol/xmpp/util/SSRCSignaling.java, src/main/java/org/jitsi/protocol/xmpp/util/SimulcastGrouping.java, src/main/java/org/jitsi/protocol/xmpp/util/SourceGroup.java
Gets rid of media type where video specific groups are in use. Other minor refactoring.
=> ref(SSRCValidator): improvements

README.md
=> Update README.md to fix #251

pom.xml, src/test/java/org/jitsi/jicofo/OSGiHandler.java
related to https://github.com/jitsi/jicoco/pull/31
=> Adds class loader for bundles

resources/mvn-exec.sh, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java, src/main/java/org/jitsi/jicofo/OctoChannelAllocator.java, src/main/java/org/jitsi/jicofo/ParticipantChannelAllocator.java, src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java, src/test/java/org/jitsi/jicofo/ColibriTest.java, src/test/java/org/jitsi/jicofo/ColibriThreadingTest.java
Depends on https://github.com/jitsi/lib-jitsi-meet/pull/730
=> feat: enableTcc, enableRemb, minParticipants.

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/recording/jibri/CommonJibriStuff.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSipGateway.java, src/main/java/org/jitsi/jicofo/recording/jibri/Utils.java, src/main/java/org/jitsi/protocol/xmpp/XmppConnection.java, src/test/java/mock/xmpp/MockXmppConnection.java, src/test/java/org/jitsi/jicofo/xmpp/JibriIqProviderTest.java
The changes here are pretty much just adapting to the ones described in [this PR](https://github.com/jitsi/jitsi/pull/475).  Will need to update the pom here after the jitsi PR is merged so don't merge this yet.
One note I'll make is that the 'retry' logic for Jibri was removed.  We were simplifying the flows a bit and decided to yank that out for now as it was based on issues with the old Jibri and I think we should verify there's still a need for it with the new Jibri now.  If we do need to add it back, it shouldn't be too hard...I just thought I'd try and simplify as much as possible for now.
=> Recording/live streaming/sip gateway signaling changes

pom.xml, src/main/java/org/jitsi/jicofo/Bridge.java, src/main/java/org/jitsi/jicofo/BridgeMucDetector.java, src/main/java/org/jitsi/jicofo/BridgeSelector.java, src/main/java/org/jitsi/jicofo/JitsiMeetServices.java, src/main/java/org/jitsi/jicofo/jigasi/JigasiDetector.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriDetector.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriEvent.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java, src/main/java/org/jitsi/jicofo/xmpp/BaseBrewery.java
This depends on jitsi/jitsi#491 (that is pom.xml has to be updated before merging).
=> Add a BridgeMucDetector

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolActivator.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/jigasi/TranscriberManager.java
jitsi-desktop-version still needs to be updated
=> implement functionality to invite transcriber when requested by client

src/main/java/org/jitsi/jicofo/JitsiMeetGlobalConfig.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSipGateway.java
don't merge until https://github.com/jitsi/jicofo/pull/336 is in
=> Max jibri retries

src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
See commit messages for more details
=> Leaking conferences

src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java
=> Revert "Adds support for signalling the video content type RTP header extension."

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/DefaultJingleRequestHandler.java, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolActivator.java, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/extensions/BridgeSessionPacketExtension.java, src/main/java/org/jitsi/impl/protocol/xmpp/extensions/IceStatePacketExtension.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/Participant.java, src/main/java/org/jitsi/jicofo/ParticipantChannelAllocator.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java, src/main/java/org/jitsi/protocol/xmpp/JingleRequestHandler.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java
Depends on https://github.com/jitsi/jitsi/pull/567
Works with https://github.com/jitsi/lib-jitsi-meet/pull/862
=> Ice failed notification

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java
The call reInviteParticipants triggered by an ICE failure notification
resulted in a synchronous call to expireChannels (while holding the lock
on #participantLock), followed by an attempt to lock #bridges in
inviteParticipant. This fix makes sure that we never lock #bridges first
and then #participants.
===================================================
"pool-1-thread-1":
at org.jitsi.jicofo.JitsiMeetConferenceImpl.reInviteParticipants(JitsiMeetConferenceImpl.java:2426)
- waiting to lock <0x0000000700ece2b8> (a java.lang.Object)
at org.jitsi.jicofo.JitsiMeetConferenceImpl.onBridgeDown(JitsiMeetConferenceImpl.java:2295)
- locked <0x0000000700ece758> (a java.util.LinkedList)
at org.jitsi.jicofo.JitsiMeetConferenceImpl.handleEvent(JitsiMeetConferenceImpl.java:2235)
at …
=> fix: Fixes a deadlock which we observed.

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java, src/main/java/org/jitsi/jicofo/FocusBundleActivator.java
Before merging, jitsi-desktop version needs to be updated after merging https://github.com/jitsi/jitsi/pull/587
=> Update ScServiceDiscoveryManager to use smacks implementation.

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/discovery/DiscoveryUtil.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java
I've been trying to investigate one issue in Jicofo lately and those logs are flooding the SEVERE level with not important things.
=> Less verbose logs

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/XmppProtocolProvider.java, src/main/java/org/jitsi/jicofo/JitsiMeetGlobalConfig.java, src/main/java/org/jitsi/jicofo/recording/jibri/CommonJibriStuff.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSipGateway.java, src/main/java/org/jitsi/protocol/xmpp/XmppConnection.java
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/15 and needs pom update after merging it
=> Recording initiator

pom.xml
This update gets the changes to move the configuration service to jitsi-utils
=> update jitsi-utils & jicoco

resources/install/debian/postinst, src/main/java/org/jitsi/jicofo/xmpp/BaseBrewery.java
Not sure which one to merge first, I think tests that test the debian package deployment will fail till we have all 3 components jitsi-meet, jicofo and jvb changes merged.
https://github.com/jitsi/jitsi-meet/pull/4956
https://github.com/jitsi/jitsi-videobridge/pull/1009
=> Migrate to using mucs for jvb

pom.xml, src/main/java/org/jitsi/jicofo/recording/jibri/CommonJibriStuff.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java, src/test/java/org/jitsi/jicofo/xmpp/JibriIqProviderTest.java
relies on https://github.com/jitsi/jitsi-xmpp-extensions/pull/16
=> Support Jibri shouldRetry field

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/osgi/JicofoBundleConfig.java, src/main/java/org/jitsi/jicofo/recording/jibri/CommonJibriStuff.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriRecorder.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSession.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSessionEvent.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriSipGateway.java, src/main/java/org/jitsi/jicofo/recording/jibri/JibriStats.java, src/main/java/org/jitsi/jicofo/rest/Statistics.java, src/main/java/org/jitsi/jicofo/stats/JicofoStatisticsSnapshot.java, src/main/java/org/jitsi/jicofo/util/EventAdminProvider.java, src/main/java/org/jitsi/jicofo/util/JibriStatsProvider.java, src/main/java/org/jitsi/jicofo/util/OsgiServiceBinder.java
The following JSON keys will be added to the stats:
"total_live_streaming_failures"
"total_recording_failures"
"total_sip_call_failures"
=> feat: add stats for total Jibri failures

src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetServices.java, src/main/java/org/jitsi/jicofo/MeetExtensionsHandler.java, src/main/java/org/jitsi/jicofo/VersionBroadcaster.java, src/main/java/org/jitsi/jicofo/bridge/Bridge.java, src/main/java/org/jitsi/jicofo/bridge/BridgeMucDetector.java, src/main/java/org/jitsi/jicofo/bridge/BridgeSelectionStrategy.java, src/main/java/org/jitsi/jicofo/bridge/BridgeSelector.java, src/main/java/org/jitsi/jicofo/bridge/IntraRegionBridgeSelectionStrategy.java, src/main/java/org/jitsi/jicofo/bridge/RegionBasedBridgeSelectionStrategy.java, src/main/java/org/jitsi/jicofo/bridge/SingleBridgeSelectionStrategy.java, src/main/java/org/jitsi/jicofo/bridge/SplitBridgeSelectionStrategy.java, src/main/java/org/jitsi/jicofo/event/BridgeEvent.java, src/main/java/org/jitsi/jicofo/jigasi/TranscriberManager.java, src/main/java/org/jitsi/jicofo/rest/Statistics.java, src/main/java/org/jitsi/jicofo/util/MaxPacketRateCalculator.java, src/test/java/org/jitsi/jicofo/MockJitsiMeetConference.java, src/test/java/org/jitsi/jicofo/bridge/BridgeSelectionStrategyTest.java, src/test/java/org/jitsi/jicofo/bridge/BridgeSelectorTest.java, src/test/java/org/jitsi/jicofo/bridge/BridgeTest.java, src/test/java/org/jitsi/jicofo/bridge/MaxBitrateCalculator.java
This PR supersedes https://github.com/jitsi/jicofo/pull/418 and implements the changes discussed in the bridge selection document.
UPDATE: You can see how the behavior changes here https://github.com/jitsi/jicofo/pull/428/commits/cbfde03c4473082951cc2edc475309d7f498d341 as this commit adapts the test case (that captures the behavior) from the previous implementation.
=> Bridge selection improvements.

README.md
For people not experienced with Java, it's not clear how to append the additional "key=value" config.
=> Clarify how to add a "key=value" in the .properties file

src/main/java/org/jitsi/jicofo/FocusBundleActivator.java
Also adds org.jitsi.jicofo.SHARED_POOL_SIZE configuration property which can be used to adjust it.
=> ref: adjust max shared pool size to 1500

src/main/java/org/jitsi/jicofo/health/Health.java
...if org.jitsi.jicofo.health.ENABLE_HEALTH_CHECKS
is not set. This also preserves the previous behavior
from before the most recent health checks refactor.
Also fixes an issue where the health checks would return
500 error instead of always success if not enabled what
was written in the docs.
=> ref(Health):  auto enable on first REST request

src/main/java/org/jitsi/jicofo/health/Health.java
=> Revert "ref(Health):  auto enable on first REST request"

pom.xml
Ref: https://github.com/jitsi/jitsi-videobridge/issues/1190
=> Bump jitsi-utils

src/main/java/org/jitsi/jicofo/auth/ShibbolethHandler.java
Set the shibboleth displayName or email attribute to the localSorage variable features/base/settings.displayName to use it in JItsi-Meet UI.
=> Set localStorage settings displayName with shibboleth attribute

README.md, debian/init.d, resources/jicofo.bat, resources/jicofo.sh, resources/mvn-exec.sh, src/main/java/org/jitsi/jicofo/Main.java
=> Don't expose password & secret in process listing

pom.xml, src/main/java/org/jitsi/jicofo/auth/AuthBundleActivator.java, src/main/resources/reference.conf
See https://github.com/jitsi/jicoco/pull/99
=> adapt to AbstractJettyBundleActivator changes

pom.xml, src/main/java/org/jitsi/jicofo/util/OsgiServiceBinder.java
see https://github.com/jitsi/jicoco/pull/109
=> adapt to jicoco changes

pom.xml, src/test/java/mock/jvb/MockVideobridge.java
Needed due to https://github.com/jitsi/jitsi-videobridge/pull/1409
=> Remove unused BundleContext arg to Videobridge#stop

pom.xml, src/main/java/org/jitsi/impl/protocol/xmpp/colibri/ColibriConferenceImpl.java, src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/protocol/xmpp/colibri/ColibriConference.java
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/31
=> feat: Passes room bare jid to conference IQ.

pom.xml, src/test/java/mock/jvb/MockVideobridge.java
Relies on https://github.com/jitsi/jitsi-videobridge/pull/1436
=> adapt to jvb changes (osgi removal)

src/main/java/org/jitsi/jicofo/bridge/Bridge.java, src/main/java/org/jitsi/jicofo/bridge/BridgeSelectionStrategy.java, src/main/kotlin/org/jitsi/jicofo/bridge/BridgeConfig.kt, src/main/resources/reference.conf, src/test/java/org/jitsi/jicofo/bridge/BridgeSelectionStrategyTest.java, src/test/java/org/jitsi/jicofo/bridge/BridgeSelectorTest.java
Depends on https://github.com/jitsi/jitsi-videobridge/pull/1440
=> Use the new JVB stress level stat

src/main/java/org/jitsi/impl/reservation/rest/RESTReservations.java, src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/auth/AbstractAuthAuthority.java
=> Handle multi focus allocator listerner

pom.xml
=> chore: Update jitsi-videobridge

src/main/java/org/jitsi/jicofo/health/JicofoHealthChecker.java
Adds a ping that will get its response in the single thread that handles the sync stanza listeners and will detect if something is blocking it.
=> feat: Adds a ping to the healthcheck.

src/main/java/org/jitsi/jicofo/JitsiMeetConferenceImpl.java, src/test/java/mock/MockParticipant.java, src/test/java/mock/muc/MockMucShare.java, src/test/java/mock/muc/MockMultiUserChat.java, src/test/java/org/jitsi/jicofo/AdvertiseSSRCsTest.java
~IMPORTANT: Before merging verify that mobile clients have been updated to remove tracks when a member leaves.~ (they have been)
=> feat: Do not send source-remove when a participant leaves.

pom.xml
to fix jitsi-videobridge unit tests.
=> update jitsi-utils version

src/main/java/org/jitsi/jicofo/codec/JingleOfferFactory.java, src/main/kotlin/org/jitsi/jicofo/codec/CodecConfig.kt, src/main/resources/reference.conf, src/test/kotlin/org/jitsi/jicofo/CodecConfigTest.kt
This PR adds support with a config option to offer support for MID header extension.
Note: the feature itself is still work in progress and doesn't work yet.
=> feat: added support for requesting MID header extensions

pom.xml
Fixes race condition in muc and fixes processing destroy messages.
=> feat: Updates smack to 4.4.4.

src/main/java/org/jitsi/impl/protocol/xmpp/ChatMemberImpl.java, src/main/java/org/jitsi/impl/protocol/xmpp/ChatRoomImpl.java
shouldn't have set per-instance context on a static logger object.
=> fix logger context.

src/main/java/org/jitsi/impl/protocol/xmpp/XmppProviderImpl.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/protocol/xmpp/AbstractOperationSetJingle.java
Fix mismatched spaces around equals signs.
=> Clean some log messages.

src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/rest/Pin.java, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v1/ColibriV1SessionManager.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt, src/test/kotlin/org/jitsi/jicofo/bridge/BridgePinTest.kt
=> Conferences can be pinned to a specific bridge version.

src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java, src/test/kotlin/org/jitsi/jicofo/conference/ParticipantInviteRunnableTest.kt
- test: Add a test for the Jingle offer sent by ParticipantInviteRunnable.
- fix: Don't include video sources if the participant has no video support
=> Fix inviting jigasi with colibri2

src/main/java/org/jitsi/jicofo/bridge/BridgeSelectionStrategy.java, src/main/java/org/jitsi/jicofo/bridge/RegionBasedBridgeSelectionStrategy.java, src/main/kotlin/org/jitsi/jicofo/bridge/BridgeConfig.kt, src/main/resources/reference.conf, src/test/kotlin/org/jitsi/jicofo/bridge/BridgeConfigTest.kt, src/test/kotlin/org/jitsi/jicofo/bridge/BridgeSelectorTest.kt, src/test/kotlin/org/jitsi/jicofo/bridge/RegionBasedSelectionTest.kt
- feat: Add region groups config.
- feat: Implement selection with region groups.
=> feat: Take into account region groups for selection.

src/main/java/org/jitsi/jicofo/jibri/JibriSession.java, src/main/kotlin/org/jitsi/jicofo/jibri/BaseJibri.kt, src/main/kotlin/org/jitsi/jicofo/xmpp/JibriIqHandler.kt
- log: Inherit log context in JibriSession.
- log: Log when at jibri IQ is dropped.
- log: Log all received jibri requests.
=> Improve jibri logs

pom.xml, src/main/java/org/jitsi/jicofo/conference/Participant.java, src/main/java/org/jitsi/jicofo/discovery/DiscoveryUtil.java, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Colibri2Session.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Extensions.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ParticipantInfo.kt
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/68
=> feat(ColibriV2): source names capability

src/main/java/org/jitsi/jicofo/conference/JitsiMeetConference.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/kotlin/org/jitsi/jicofo/xmpp/MuteIqHandler.kt
- ref: Make muterJid non-nullable.
- ref: Make more fields non-nullable.
=> ref: Make fields non-nullable

src/main/java/org/jitsi/jicofo/bridge/RegionBasedBridgeSelectionStrategy.java, src/main/java/org/jitsi/jicofo/bridge/SplitBridgeSelectionStrategy.java
=> log: Warn when octo is disabled

src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/conference/Participant.java, src/main/java/org/jitsi/jicofo/conference/ParticipantInviteRunnable.java, src/main/java/org/jitsi/jicofo/discovery/DiscoveryUtil.java, src/test/java/org/jitsi/jicofo/JigasiSelectorTest.java, src/test/kotlin/org/jitsi/jicofo/conference/ParticipantInviteRunnableTest.kt
- ref: Use java9+ List.of for an unmodifiable list.
- fix: Fix detection of audio mute support.
=> fix: Fix detection of audio mute support.

src/main/java/org/jitsi/jicofo/FocusManager.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/stats/Statistics.java
- ref: Remove the "bridges removed" metric (redundant).
- ref: Remove unused destroyConference method.
=> Remove the "bridges removed" metric.

src/main/java/org/jitsi/jicofo/bridge/RegionBasedBridgeSelectionStrategy.java, src/main/kotlin/org/jitsi/jicofo/bridge/BridgeSelector.kt, src/test/kotlin/org/jitsi/jicofo/bridge/RegionBasedSelectionTest.kt
- feat: Default to localRegion when participantRegion is null.
- test: Add a test for initial selection in region group.
- feat: Prefer local region for initial selection.
- doc: Cleanup docs.
=> Prefer local region for initial selection

src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Colibri2Session.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/ColibriV2SessionManager.kt, src/main/kotlin/org/jitsi/jicofo/conference/colibri/v2/Extensions.kt
or any request receives an error response.
=> fix: Remove bridge when "create relay" times out

spotbugs-exclude.xml, src/main/java/org/jitsi/jicofo/Main.java, src/main/java/org/jitsi/jicofo/bridge/JvbDoctor.java, src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, src/main/java/org/jitsi/jicofo/health/JicofoHealthChecker.java, src/main/java/org/jitsi/jicofo/rest/Debug.java, src/main/java/org/jitsi/jicofo/rest/Pin.java, src/main/java/org/jitsi/jicofo/rest/Statistics.java, src/main/kotlin/org/jitsi/jicofo/JicofoServices.kt, src/main/kotlin/org/jitsi/jicofo/util/SynchronizedDelegate.kt, src/test/java/org/jitsi/jicofo/JicofoHarness.java
=> fix: Do not access the JicofoServices singleton before it has initialized.

jicofo-selector/src/main/java/org/jitsi/jicofo/bridge/BridgeSelectionStrategy.java, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/BridgeSelector.kt
- log: Log selection at INFO.
- Add metric for the number of different bridge versions available.
=> Bridge selection logs and metric tweaks

jicofo-common/src/main/kotlin/org/jitsi/jicofo/conference/source/ValidatingConferenceSourceMap.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/test/kotlin/org/jitsi/jicofo/SsrcValidationPerfTest.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/ValidatingConferenceSourceMapTest.kt
- fix: Fix adding empty sources.
- ref: Return EndpointSourceSet from tryTo{add,Remove}.
=> Fix handling empty sources.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/codec/CodecConfig.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/codec/CodecUtil.kt, jicofo-selector/src/main/resources/reference.conf, jicofo/src/test/kotlin/org/jitsi/jicofo/CodecConfigTest.kt
=> feat: generate AV1 SDP in Jicofo

jicofo/src/main/kotlin/org/jitsi/jicofo/FocusManager.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/JicofoServices.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/jibri/JibriDetector.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/jibri/JibriDetectorMetrics.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/jigasi/JigasiDetector.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppServices.kt
- fix: Disentangle jibri/sip_jibri metrics.
- feat: Expose jigasi stats as prometheus metrics.
=> Port jigasi metrics, fix jibri metrics

jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/Colibri2Session.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt
- Include this.relayId in thrown exceptions
- log: Log joining members' chat room.
- log: Log more details for conference request, redirect to vnode.
=> Add additional logs.

jicofo/src/main/kotlin/org/jitsi/jicofo/conference/ConferenceUtil.kt
=> Use visitors mode even when over the limit.

jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConference.java, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/conference/Participant.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/rest/RtcStats.kt, jicofo/src/test/kotlin/org/jitsi/jicofo/conference/ConferenceTest.kt
- fix: Do not include chatMember under participant, they are already under chat room.
- feat: Add an /rtcstats endpoint.
=> Add an /rtcstats endpoint for stats to be exported to rtcstats.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoom.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConference.java, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/FocusManager.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/JicofoServices.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomRoleManager.kt
- ref: Replace ExpireThread with a scheduled timeout.
- feat: Do not stop a conference until all breakout conferences have ended.
=>  Do not stop a conference until all breakout conferences have ended.

pom.xml
=> Update jitsi-xmpp-extensions and jitsi-utils.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/jingle/JingleSession.kt, jicofo-selector/pom.xml, jicofo/pom.xml, jicofo/spotbugs-exclude.xml, pom.xml
Apply ktlint fixes from ktlint 0.50.0.
=> Update Kotlin to 1.9.10, and related Maven packages.

debian/control
Reverts 8b0e03d and adds java17.
=> feat: Updates java dependencies to include java17.

jicofo-common/pom.xml, jicofo-selector/pom.xml, jicofo/pom.xml, pom.xml
Also remove some no-longer-used dependencies.
=> Update Jetty (including through jicoco dependency).

jicofo-common/src/main/kotlin/org/jitsi/jicofo/metrics/GlobalMetrics.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppProvider.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/JicofoServices.kt
- **ref: Rename the threads metric variable.**
- **feat: Add a metric for XMPP disconnects.**
=> feat: Add a metric for XMPP disconnects.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppProvider.kt
In case prosody is not fully up we can receive StreamErrorException: invalid-namespace and at the same time we are connected which will cause reconnection to stop.
=> fix(reconnect): Handle reconnect too quickly and fail.

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/XmppProvider.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/jingle/JingleSession.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/BridgeSelectionStrategy.kt, jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriV2SessionManager.kt
- **fix: Do not override log level for brewery rooms.**
- **Remove topology strategy log, too verbose.**
- **log: Move some logs from INFO to DEBUG.**
=> Reduce excessive logging

jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoom.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/ChatRoomImpl.kt, jicofo-common/src/main/kotlin/org/jitsi/jicofo/xmpp/muc/RoomMetadata.kt, jicofo-common/src/test/kotlin/org/jitsi/jicofo/xmpp/muc/RoomMetadataTest.kt, jicofo/pom.xml, jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java, jicofo/src/main/kotlin/org/jitsi/jicofo/ConferenceRequest.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/ktor/Application.kt, jicofo/src/main/kotlin/org/jitsi/jicofo/xmpp/ConferenceIqHandler.kt, pom.xml
- **feat: Read conference request token.**
- **feat: Parse mainRoomParticipants from metadata.**
- **feat: Send main room participants to main room.**
- **chore: Bump jicoco.**
=> feat: Read list of main room participants, do not redirect them.
